// src/modules/ai/index.ts

export { aiRouter } from "./ai.router"
export { aiFunctions } from "./ai.events"
export { aiService } from "./ai.service"
export { agentActionsRepository } from "./ai.actions.repository"
export { aiConfigRepository } from "./ai.config.repository"
export { generateWorkflowFromDescription } from "./ai.workflow-generator"
export { suggestionsRepository } from "./ai.suggestions.repository"
export { knowledgeRepository } from "./knowledge/repository"
export { correctionsRepository } from "./memory/corrections"
export { hotMemory } from "./memory/hot"
export { getVerticalProfile, listVerticalProfiles } from "./verticals"
export { mcpConnectionRepository } from "./mcp/repository"
export { discoverTools, callExternalTool, checkConnectionHealth } from "./mcp/client"
export { getExternalToolsForTenant, adaptExternalTools } from "./mcp/adapter"
export { extractEntities } from "./features/paste-to-pipeline"
export { commitEntities } from "./features/paste-to-pipeline.commit"
export { gatherBriefingData } from "./features/morning-briefing.data"
export { generateBriefing } from "./features/morning-briefing.generator"
export { processGhostOperator } from "./features/ghost-operator.processor"
export type { MCPConnectionRecord, MCPToolDefinition, MCPApiKeyScope, JsonRpcRequest, JsonRpcResponse } from "./mcp/types"
export type { ExternalToolEntry } from "./mcp/adapter"
export type { AgentTool, AgentContext, ConversationRecord, MessageRecord, AgentResponse, GuardrailTier, TenantAIConfig, VerticalProfile, CorrectionRecord, KnowledgeChunkRecord, RAGResult, MorningBriefing, BriefingMetrics, GhostOperatorRule, GhostOperatorResult, ExtractedEntities } from "./ai.types"
