export type PropertyType = "Office" | "Retail" | "Industrial" | "Trade Counter" | "Leisure"
export type StatusType = "Available" | "Under Offer" | "Let Agreed" | "Stc"
export type ActivityType = "enquiry" | "viewing" | "offer" | "status_change" | "note" | "marketing"

export interface ActivityEntry {
  date: string
  type: ActivityType
  text: string
  agent?: string
  detail?: string
}

export interface ListingDetail {
  id: number
  property: string
  location: string
  type: PropertyType
  size: string
  sizeSqft: number
  asking: string
  daysOnMarket: number
  enquiries: number
  viewings: number
  status: StatusType
  fullAddress: string
  tenure: "Leasehold" | "Freehold"
  epc: string
  availableFrom: string
  description: string
  landlordName: string
  landlordContact: string
  agentInitials: string
  floorLevel?: string
  parkingSpaces: number
  rateable?: string
  dealIds?: string[]
  activity: ActivityEntry[]
}

export const LISTINGS: ListingDetail[] = [
  {
    id: 1,
    property: "Unit 3 Axis Court",
    location: "Swansea Enterprise Park",
    type: "Office",
    size: "1,240",
    sizeSqft: 1240,
    asking: "£14,500 pa",
    daysOnMarket: 12,
    enquiries: 8,
    viewings: 4,
    status: "Available",
    fullAddress: "Unit 3 Axis Court, Swansea Enterprise Park, Llansamlet, Swansea, SA7 9FG",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Immediate",
    description: "Modern self-contained office suite within the popular Swansea Enterprise Park, offering excellent access to the M4 at Junction 44. The accommodation comprises open-plan space with a dedicated reception area, two meeting rooms, and a kitchenette. Generous on-site parking is available and the unit benefits from recent refurbishment throughout.",
    landlordName: "Axis Commercial Estates Ltd",
    landlordContact: "Mr G. Harrington - 01792 654 321",
    agentInitials: "DB",
    floorLevel: "Ground Floor",
    parkingSpaces: 8,
    rateable: "£9,200",
    dealIds: [],
    activity: [
      { date: "2026-02-20", type: "marketing", text: "Property listed on CoStar and Rightmove Commercial. Brochure distributed to 140 active occupier contacts.", agent: "DB" },
      { date: "2026-02-22", type: "enquiry", text: "Enquiry received from a professional services firm seeking 1,000–1,500 sqft in the Swansea Enterprise Park area.", agent: "DB", detail: "Initial contact via CoStar. Budget aligned. Requested brochure and EPC." },
      { date: "2026-02-24", type: "enquiry", text: "Second enquiry from a tech startup looking to relocate from the city centre.", agent: "DB" },
      { date: "2026-02-25", type: "enquiry", text: "Enquiry from a chartered accountancy practice - size requirement 1,000–1,500 sqft, ideally with parking.", agent: "DB" },
      { date: "2026-02-26", type: "viewing", text: "Viewing conducted with professional services firm. Strong interest expressed. Reviewing fit-out requirements.", agent: "DB", detail: "Attendees: two directors and office manager. Requested floor plans for internal sign-off." },
      { date: "2026-02-28", type: "viewing", text: "Viewing with tech startup - positive feedback. Considering alongside another unit in the park.", agent: "DB" },
      { date: "2026-03-01", type: "enquiry", text: "Further enquiry received via email from a construction consultancy.", agent: "DB" },
      { date: "2026-03-03", type: "viewing", text: "Second viewing with professional services firm. Lease terms discussed informally.", agent: "DB" },
    ],
  },
  {
    id: 2,
    property: "Ground Floor Suite, Sophia House",
    location: "Cardiff",
    type: "Office",
    size: "850",
    sizeSqft: 850,
    asking: "£12,000 pa",
    daysOnMarket: 28,
    enquiries: 5,
    viewings: 2,
    status: "Available",
    fullAddress: "Ground Floor Suite, Sophia House, 28 Cathedral Road, Cardiff, CF11 9LJ",
    tenure: "Leasehold",
    epc: "D",
    availableFrom: "Immediate",
    description: "Attractive ground-floor office suite within a period property on prestigious Cathedral Road, close to Pontcanna and within walking distance of Cardiff city centre. The suite provides open-plan accommodation with original period features including high ceilings and sash windows. Suitable for small professional firms, consultancies, or creative practices.",
    landlordName: "Cathedral Road Property Holdings",
    landlordContact: "Ms A. Griffiths - 029 2045 6789",
    agentInitials: "RJ",
    floorLevel: "Ground Floor",
    parkingSpaces: 2,
    rateable: "£7,800",
    dealIds: [],
    activity: [
      { date: "2026-02-04", type: "marketing", text: "Property launched to market. Listing placed on Rightmove Commercial and local agent network.", agent: "RJ" },
      { date: "2026-02-08", type: "enquiry", text: "Enquiry from a Cardiff-based solicitors seeking a satellite office to serve Pontcanna clients.", agent: "RJ", detail: "Looking for 6–12 month initial term with option to renew." },
      { date: "2026-02-13", type: "enquiry", text: "Enquiry from architectural practice - currently home-based, looking to establish a studio presence.", agent: "RJ" },
      { date: "2026-02-17", type: "viewing", text: "Viewing conducted with solicitors. Positive response to the period character of the building.", agent: "RJ", detail: "Requested confirmation of broadband capacity and car parking details." },
      { date: "2026-02-24", type: "enquiry", text: "Enquiry via Rightmove from a healthcare consultancy.", agent: "RJ" },
      { date: "2026-03-01", type: "viewing", text: "Viewing with architectural practice - keen on the space but flagged limited parking as a concern.", agent: "RJ" },
    ],
  },
  {
    id: 3,
    property: "Bridgend Business Centre, Suite 7",
    location: "Bridgend",
    type: "Office",
    size: "620",
    sizeSqft: 620,
    asking: "£8,200 pa",
    daysOnMarket: 45,
    enquiries: 3,
    viewings: 1,
    status: "Available",
    fullAddress: "Suite 7, Bridgend Business Centre, Tremains Road, Bridgend, CF31 1TZ",
    tenure: "Leasehold",
    epc: "E",
    availableFrom: "Immediate",
    description: "Compact and affordable office suite within a managed business centre environment, ideal for small businesses and sole practitioners. The suite benefits from shared reception, communal meeting rooms, and on-site café facilities managed by the centre. Flexible lease terms are available to accommodate growing businesses.",
    landlordName: "Bridgend Business Centre Management Ltd",
    landlordContact: "Mr P. Evans - 01656 768 400",
    agentInitials: "DB",
    floorLevel: "First Floor",
    parkingSpaces: 3,
    rateable: "£5,600",
    dealIds: [],
    activity: [
      { date: "2026-01-18", type: "marketing", text: "Suite relisted following tenant departure. Refreshed brochure and updated photography arranged.", agent: "DB" },
      { date: "2026-01-27", type: "enquiry", text: "Enquiry from a freelance HR consultant seeking a permanent business address with meeting room access.", agent: "DB" },
      { date: "2026-02-05", type: "enquiry", text: "Enquiry from a two-person insurance brokerage considering expansion from home working.", agent: "DB" },
      { date: "2026-02-12", type: "viewing", text: "Viewing with insurance brokerage. Feedback positive but budget slightly under asking.", agent: "DB", detail: "Requested landlord's position on a slight rent reduction or rent-free period." },
      { date: "2026-02-20", type: "note", text: "Landlord advised willing to offer 1 month rent-free on a 3-year lease. DB to relay to prospective tenants.", agent: "DB" },
      { date: "2026-03-01", type: "enquiry", text: "New enquiry received from a sole-trader accountant.", agent: "DB" },
    ],
  },
  {
    id: 4,
    property: "Meridian Point",
    location: "Neath",
    type: "Office",
    size: "3,400",
    sizeSqft: 3400,
    asking: "£34,000 pa",
    daysOnMarket: 67,
    enquiries: 11,
    viewings: 6,
    status: "Under Offer",
    fullAddress: "Meridian Point, Brunel Way, Baglan Energy Park, Neath, SA11 2FP",
    tenure: "Leasehold",
    epc: "B",
    availableFrom: "Under Offer",
    description: "Prominent detached office building forming part of the Baglan Energy Park, offering modern Grade A specification including raised access floors, VRF air conditioning, and a prestigious glazed entrance reception. The building provides flexible open-plan floor plates with cellular office capability and commands excellent profile from the A48 Port Talbot Road. Under offer - best-and-final process concluded.",
    landlordName: "Meridian Park Developments Ltd",
    landlordContact: "Mr R. Hutchings - 01639 820 100",
    agentInitials: "DB",
    floorLevel: "Two Floors",
    parkingSpaces: 28,
    rateable: "£22,500",
    dealIds: ["u4"],
    activity: [
      { date: "2025-12-29", type: "marketing", text: "Property relaunched following previous tenant exit. Full marketing campaign initiated including CoStar Premium and targeted email to 200+ occupiers.", agent: "DB" },
      { date: "2026-01-05", type: "enquiry", text: "Enquiry from an energy sector company seeking a regional HQ in the Neath/Port Talbot area.", agent: "DB" },
      { date: "2026-01-08", type: "enquiry", text: "Enquiry from a public sector body looking for secondary office space.", agent: "DB" },
      { date: "2026-01-12", type: "viewing", text: "Viewing with energy sector company - very positive. Requesting schedule of condition.", agent: "DB", detail: "Interested in entire building. Would need fit-out contribution discussion." },
      { date: "2026-01-19", type: "viewing", text: "Viewing with professional services firm (4 decision-makers attended). Considering for regional hub.", agent: "DB" },
      { date: "2026-01-28", type: "viewing", text: "Second viewing with energy sector company - structural engineer attended.", agent: "DB" },
      { date: "2026-02-06", type: "offer", text: "Formal offer received from Connective Energy Services Ltd at £31,500 pa on a 5-year lease with a 6-month rent-free period.", agent: "DB", detail: "Heads of Terms issued. Solicitors instructed on both sides." },
      { date: "2026-02-14", type: "status_change", text: "Status updated to Under Offer. Property withdrawn from active marketing.", agent: "DB" },
    ],
  },
  {
    id: 5,
    property: "First Floor, Kingsway",
    location: "Swansea",
    type: "Office",
    size: "1,800",
    sizeSqft: 1800,
    asking: "£22,500 pa",
    daysOnMarket: 19,
    enquiries: 7,
    viewings: 3,
    status: "Available",
    fullAddress: "First Floor, 42–44 Kingsway, Swansea City Centre, Swansea, SA1 5LE",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Immediate",
    description: "Prominent first-floor office suite in a central Kingsway location with excellent footfall and profile in the heart of Swansea city centre. The refurbished accommodation provides open-plan workspace, a boardroom, and staff welfare facilities including a fully fitted kitchen. The building benefits from lift access and is situated directly opposite the Civic Centre.",
    landlordName: "Swansea City Estates Ltd",
    landlordContact: "Mr D. Thomas - 01792 480 950",
    agentInitials: "DB",
    floorLevel: "First Floor",
    parkingSpaces: 4,
    rateable: "£14,000",
    dealIds: [],
    activity: [
      { date: "2026-02-13", type: "marketing", text: "Listing placed on CoStar and local office network. Press release issued to South Wales Business Daily.", agent: "DB" },
      { date: "2026-02-15", type: "enquiry", text: "Enquiry from a digital marketing agency seeking city centre office presence.", agent: "DB" },
      { date: "2026-02-17", type: "enquiry", text: "Enquiry from a recruitment firm looking to relocate from Cardiff to Swansea.", agent: "DB" },
      { date: "2026-02-19", type: "enquiry", text: "Enquiry from a housing association needing satellite administrative office.", agent: "DB", detail: "Flexible lease preferred - asking about 12-month break option." },
      { date: "2026-02-21", type: "viewing", text: "Viewing with digital marketing agency - enthusiastic response. Considering alongside a ground-floor retail unit on Wind Street.", agent: "DB" },
      { date: "2026-02-26", type: "viewing", text: "Viewing with recruitment firm. Decision expected within two weeks.", agent: "DB" },
      { date: "2026-03-01", type: "viewing", text: "Viewing with housing association - measuring for layout planning.", agent: "DB" },
    ],
  },
  {
    id: 6,
    property: "Sketty Lane Commercial",
    location: "Swansea",
    type: "Office",
    size: "950",
    sizeSqft: 950,
    asking: "£14,000 pa",
    daysOnMarket: 8,
    enquiries: 4,
    viewings: 2,
    status: "Available",
    fullAddress: "Sketty Lane Commercial, 18 Sketty Lane, Uplands, Swansea, SA2 0EU",
    tenure: "Leasehold",
    epc: "D",
    availableFrom: "Immediate",
    description: "Recently vacated office suite in a well-regarded suburban commercial location between Uplands and Sketty, with easy access to the M4 and Swansea Bay. The self-contained ground floor accommodation includes a reception area, three private offices, and a comfortable breakout space. On-site parking for up to six vehicles is included within the rent.",
    landlordName: "Uplands Commercial Property Ltd",
    landlordContact: "Mr B. Jones - 01792 290 175",
    agentInitials: "DB",
    floorLevel: "Ground Floor",
    parkingSpaces: 6,
    rateable: "£9,000",
    dealIds: [],
    activity: [
      { date: "2026-02-24", type: "marketing", text: "Property brought to market. Circulated to occupier database and listed on Rightmove Commercial.", agent: "DB" },
      { date: "2026-02-26", type: "enquiry", text: "Enquiry from a physiotherapy practice looking for clinical and administrative space.", agent: "DB" },
      { date: "2026-02-28", type: "enquiry", text: "Enquiry from an estate agency exploring branch expansion to Swansea west.", agent: "DB" },
      { date: "2026-03-01", type: "viewing", text: "Viewing with physiotherapy practice - strong interest. Requested landlord's view on internal alterations.", agent: "DB", detail: "Would need to install a treatment room partition. Landlord consent to be sought." },
      { date: "2026-03-03", type: "viewing", text: "Viewing with estate agency - very positive. Short listed with one other property.", agent: "DB" },
    ],
  },
  {
    id: 7,
    property: "45 High Street",
    location: "Llanelli",
    type: "Retail",
    size: "1,100",
    sizeSqft: 1100,
    asking: "£18,500 pa",
    daysOnMarket: 34,
    enquiries: 6,
    viewings: 3,
    status: "Available",
    fullAddress: "45 High Street, Llanelli Town Centre, Llanelli, SA15 1HL",
    tenure: "Leasehold",
    epc: "E",
    availableFrom: "Immediate",
    description: "Mid-terrace retail unit on the pedestrianised section of Llanelli High Street, offering prominent glazed frontage and good ground-floor trading space with ancillary storage to the rear. The unit benefits from an established position between well-known national retailers and enjoys strong footfall from the adjacent bus interchange and car park. A Grade II listed building - suitable for a range of retail and service uses.",
    landlordName: "Llanelli Town Centre REIT Ltd",
    landlordContact: "Ms C. Williams - 01554 779 000",
    agentInitials: "MW",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£12,000",
    dealIds: [],
    activity: [
      { date: "2026-01-29", type: "marketing", text: "Unit listed following previous occupier exit. Brochure and floor plan prepared. Rightmove Commercial and EGi listings placed.", agent: "MW" },
      { date: "2026-02-03", type: "enquiry", text: "Enquiry from an independent gift and homewares retailer looking to expand to Llanelli.", agent: "MW" },
      { date: "2026-02-09", type: "enquiry", text: "Enquiry from a national coffee chain scouting secondary town centre locations.", agent: "MW", detail: "National covenant - landlord keen. However, chain requires revised frontage - planning assessment pending." },
      { date: "2026-02-14", type: "viewing", text: "Viewing with gift and homewares retailer. Liked the space but raised concern about rear access for deliveries.", agent: "MW" },
      { date: "2026-02-19", type: "enquiry", text: "Enquiry from a mobile phone repair franchise.", agent: "MW" },
      { date: "2026-02-25", type: "viewing", text: "Viewing with mobile phone repair franchise - very interested, measuring for fit-out.", agent: "MW" },
      { date: "2026-03-02", type: "viewing", text: "Viewing with independent clothing boutique - also sourcing locations in Carmarthen and Neath.", agent: "MW" },
    ],
  },
  {
    id: 8,
    property: "Unit 2 Parc Tawe",
    location: "Swansea",
    type: "Retail",
    size: "2,800",
    sizeSqft: 2800,
    asking: "£42,000 pa",
    daysOnMarket: 52,
    enquiries: 4,
    viewings: 2,
    status: "Let Agreed",
    fullAddress: "Unit 2 Parc Tawe Retail Park, Quay Parade, Swansea, SA1 1TU",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Let Agreed",
    description: "Well-configured retail warehouse unit within the established Parc Tawe Retail Park, benefiting from extensive shared car parking, prominent signage opportunities, and strong anchors including B&M and The Range. The unit has a wide open trading floor and is let agreed to a regional homeware operator on a new 10-year lease with 5-year break.",
    landlordName: "Parc Tawe Retail Park Estates",
    landlordContact: "Mr T. Davies - 01792 310 600",
    agentInitials: "MW",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£28,500",
    dealIds: ["c2"],
    activity: [
      { date: "2026-01-10", type: "marketing", text: "Unit relaunched to market with CoStar Premium profile and Out-of-Town Retail database campaign.", agent: "MW" },
      { date: "2026-01-17", type: "enquiry", text: "Enquiry from a national floor and tile retailer seeking a Swansea location.", agent: "MW" },
      { date: "2026-01-24", type: "enquiry", text: "Enquiry from a regional furniture and homewares group - strong covenant.", agent: "MW", detail: "Requested schedule of condition, service charge details, and loading bay measurements." },
      { date: "2026-01-31", type: "viewing", text: "Viewing with furniture and homewares group - two directors and a surveyor attended.", agent: "MW", detail: "Very positive. Board approval needed before formal offer." },
      { date: "2026-02-10", type: "offer", text: "Formal offer received from Welland Home Furnishings Ltd at £40,000 pa on a 10-year lease with 5-year break and 6-month rent-free.", agent: "MW", detail: "Heads of Terms agreed. Solicitors instructed." },
      { date: "2026-02-21", type: "status_change", text: "Let Agreed confirmed. Exchange of contracts completed. Rent-free period commences 1 March 2026.", agent: "MW" },
    ],
  },
  {
    id: 9,
    property: "112 Queen Street",
    location: "Cardiff",
    type: "Retail",
    size: "600",
    sizeSqft: 600,
    asking: "£28,000 pa",
    daysOnMarket: 14,
    enquiries: 9,
    viewings: 5,
    status: "Available",
    fullAddress: "112 Queen Street, Cardiff City Centre, Cardiff, CF10 2EN",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Immediate",
    description: "Compact and well-presented retail unit in a prime position on Cardiff's pedestrianised Queen Street, one of the busiest retail thoroughfares in Wales. The unit benefits from exceptional footfall generated by proximity to Cardiff Central station, the St David's shopping centre, and the Queen Street Arcade. Ideal for fashion, beauty, F&B, or specialist retail operators.",
    landlordName: "Cardiff Prime Retail Ltd",
    landlordContact: "Ms E. Morgan - 029 2065 4400",
    agentInitials: "RJ",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£19,500",
    dealIds: [],
    activity: [
      { date: "2026-02-18", type: "marketing", text: "Unit brought to market. High-footfall position marketed directly to national retail operators and franchise networks.", agent: "RJ" },
      { date: "2026-02-19", type: "enquiry", text: "Enquiry from a cosmetics brand seeking a Cardiff flagship location.", agent: "RJ" },
      { date: "2026-02-20", type: "enquiry", text: "Enquiry from a mobile accessories national chain.", agent: "RJ" },
      { date: "2026-02-20", type: "enquiry", text: "Enquiry from a jewellery retailer with three existing South Wales stores.", agent: "RJ", detail: "Strong covenant. Looking for a minimum 5-year term." },
      { date: "2026-02-21", type: "viewing", text: "Viewing with cosmetics brand - head of property and area manager attended.", agent: "RJ" },
      { date: "2026-02-24", type: "viewing", text: "Viewing with jewellery retailer - measured up for shopfit design.", agent: "RJ" },
      { date: "2026-02-26", type: "enquiry", text: "Enquiry from a watch and sunglasses concession operator.", agent: "RJ" },
      { date: "2026-03-01", type: "viewing", text: "Viewing with mobile accessories chain - decision expected imminently.", agent: "RJ" },
    ],
  },
  {
    id: 10,
    property: "Bridgend Retail Park, Unit 8",
    location: "Bridgend",
    type: "Retail",
    size: "4,500",
    sizeSqft: 4500,
    asking: "£56,000 pa",
    daysOnMarket: 89,
    enquiries: 2,
    viewings: 1,
    status: "Available",
    fullAddress: "Unit 8 Bridgend Retail Park, Brackla Way, Bridgend, CF31 2AF",
    tenure: "Leasehold",
    epc: "D",
    availableFrom: "Immediate",
    description: "Large out-of-town retail warehouse unit within Bridgend Retail Park, with excellent access to the M4 at Junction 35 and extensive free surface-level car parking serving the park. The unit offers wide open trading floor space suitable for bulky goods, DIY, leisure, or furniture operations. A number of national retailers trade from the same park.",
    landlordName: "Bridgend Retail Investments plc",
    landlordContact: "Mr A. Pearce - 01656 650 200",
    agentInitials: "MW",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£36,000",
    dealIds: [],
    activity: [
      { date: "2025-12-05", type: "marketing", text: "Unit relaunched to market. Rightmove, CoStar, and Out-of-Town Retail network listings placed.", agent: "MW" },
      { date: "2026-01-08", type: "enquiry", text: "Enquiry from a national pet retail chain reviewing portfolio expansion.", agent: "MW", detail: "Requested demographic data and footfall counts for the park. Sent in January." },
      { date: "2026-01-23", type: "viewing", text: "Viewing with pet retail chain - accompanied by property director.", agent: "MW", detail: "Positive feedback on the unit but board review required. No further contact since." },
      { date: "2026-02-15", type: "enquiry", text: "Enquiry from a regional trade and DIY operator.", agent: "MW" },
      { date: "2026-03-01", type: "note", text: "Follow-up call made to pet retail chain - awaiting board decision. DIY operator to arrange viewing in coming weeks.", agent: "MW" },
    ],
  },
  {
    id: 11,
    property: "Pontardawe High Street",
    location: "Pontardawe",
    type: "Retail",
    size: "780",
    sizeSqft: 780,
    asking: "£11,000 pa",
    daysOnMarket: 23,
    enquiries: 5,
    viewings: 3,
    status: "Under Offer",
    fullAddress: "14 Herbert Street, Pontardawe, Swansea, SA8 4EB",
    tenure: "Leasehold",
    epc: "E",
    availableFrom: "Under Offer",
    description: "Attractive mid-terrace retail unit on Pontardawe's busy high street, benefiting from an active local catchment and proximity to the Pontardawe Sports Centre and secondary school. The unit offers open-plan ground-floor trading space with a useful rear preparation or storage room. Now under offer to an independent food and beverage operator.",
    landlordName: "Herbert Street Properties Ltd",
    landlordContact: "Mr S. Morgan - 01792 864 555",
    agentInitials: "MW",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£7,200",
    dealIds: [],
    activity: [
      { date: "2026-02-09", type: "marketing", text: "Property listed on Rightmove Commercial and local commercial network. Social media campaign launched.", agent: "MW" },
      { date: "2026-02-13", type: "enquiry", text: "Enquiry from a independent barber and grooming studio.", agent: "MW" },
      { date: "2026-02-15", type: "enquiry", text: "Enquiry from a local bakery looking for a second premises.", agent: "MW" },
      { date: "2026-02-17", type: "viewing", text: "Viewing with bakery operator - measured for counter and display unit layout.", agent: "MW" },
      { date: "2026-02-20", type: "viewing", text: "Viewing with barber studio operator. Very positive feedback.", agent: "MW" },
      { date: "2026-02-23", type: "offer", text: "Offer received from Artisan Bakehouse Ltd at £10,500 pa on a 3-year lease.", agent: "MW", detail: "Landlord accepted subject to references. Solicitors instructed." },
      { date: "2026-03-03", type: "status_change", text: "Status updated to Under Offer. Heads of Terms issued. Awaiting solicitor exchange.", agent: "MW" },
    ],
  },
  {
    id: 12,
    property: "Unit 12, Baglan Energy Park",
    location: "Port Talbot",
    type: "Industrial",
    size: "8,500",
    sizeSqft: 8500,
    asking: "£42,500 pa",
    daysOnMarket: 31,
    enquiries: 7,
    viewings: 4,
    status: "Available",
    fullAddress: "Unit 12 Baglan Energy Park, Seaway Parade, Baglan, Port Talbot, SA12 7BR",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Immediate",
    description: "Modern detached industrial/warehouse unit on the prestigious Baglan Energy Park, offering high eaves clearance of 8m, three-phase power, a single grade-level loading door, and a separate pedestrian entrance with integral two-storey office. The unit is set within a secure, well-managed estate with 24-hour gated access and benefits from good road links to the M4 at Junction 41.",
    landlordName: "Baglan Energy Park Management Company",
    landlordContact: "Mr C. Rees - 01639 890 040",
    agentInitials: "RJ",
    parkingSpaces: 12,
    rateable: "£28,000",
    dealIds: ["u2"],
    activity: [
      { date: "2026-02-01", type: "marketing", text: "Unit placed on CoStar Industrial Database and South Wales Industrial Network circular.", agent: "RJ" },
      { date: "2026-02-05", type: "enquiry", text: "Enquiry from a logistics and distribution company seeking a Port Talbot/Swansea base.", agent: "RJ", detail: "Requires 6m eaves minimum and level loading. Unit satisfies both criteria." },
      { date: "2026-02-09", type: "enquiry", text: "Enquiry from a manufacturing SME in the renewable energy supply chain.", agent: "RJ" },
      { date: "2026-02-13", type: "viewing", text: "Viewing with logistics company - operations director and transport manager attended.", agent: "RJ", detail: "Very positive. Requested schedule of condition and electricity supply capacity details." },
      { date: "2026-02-18", type: "enquiry", text: "Enquiry from a waste management and recycling operator.", agent: "RJ" },
      { date: "2026-02-21", type: "viewing", text: "Viewing with renewable energy supply chain manufacturer - two directors attended.", agent: "RJ" },
      { date: "2026-02-26", type: "viewing", text: "Viewing with a vehicle conversion company from the Midlands.", agent: "RJ" },
      { date: "2026-03-02", type: "viewing", text: "Second viewing with logistics company - lease terms discussed informally. Offer expected.", agent: "RJ" },
    ],
  },
  {
    id: 13,
    property: "Cross Hands Industrial Estate",
    location: "Cross Hands",
    type: "Industrial",
    size: "14,200",
    sizeSqft: 14200,
    asking: "£71,000 pa",
    daysOnMarket: 18,
    enquiries: 12,
    viewings: 6,
    status: "Available",
    fullAddress: "Unit A, Cross Hands Industrial Estate, Cross Hands Road, Cross Hands, Llanelli, SA14 6RS",
    tenure: "Leasehold",
    epc: "B",
    availableFrom: "Immediate",
    description: "Substantial modern industrial building in a prime mid-Wales gateway location, offering outstanding connectivity via the A48 and M4 at Junction 49. The building provides a clear-span warehouse with 10m eaves, six level-access loading doors, 3-phase power, and a two-storey office wing. The estate is well-established and hosts a number of national manufacturers and logistics operators.",
    landlordName: "Hywel Dda Industrial Properties Ltd",
    landlordContact: "Mr J. Lewis - 01269 844 200",
    agentInitials: "RJ",
    parkingSpaces: 30,
    rateable: "£48,000",
    dealIds: [],
    activity: [
      { date: "2026-02-14", type: "marketing", text: "Major marketing campaign launched - CoStar headline, JLL Industrial circular, and direct approach to 50 mid-Wales manufacturers.", agent: "RJ" },
      { date: "2026-02-16", type: "enquiry", text: "Enquiry from a national grocery distribution company.", agent: "RJ", detail: "Requires minimum 12,000 sqft with 10m eaves. Unit satisfies." },
      { date: "2026-02-17", type: "enquiry", text: "Enquiry from a Welsh Government-funded advanced manufacturing company.", agent: "RJ" },
      { date: "2026-02-18", type: "enquiry", text: "Two further enquiries - automotive components supplier and a packaging company.", agent: "RJ" },
      { date: "2026-02-19", type: "viewing", text: "Viewing with grocery distribution company - head of property attended.", agent: "RJ" },
      { date: "2026-02-21", type: "viewing", text: "Viewing with advanced manufacturing company - positive feedback.", agent: "RJ" },
      { date: "2026-02-24", type: "viewing", text: "Viewing with automotive supplier - two viewings on same day, different parties.", agent: "RJ" },
      { date: "2026-03-01", type: "viewing", text: "Second viewing with grocery distribution company - surveyor and operations director.", agent: "RJ", detail: "Offer process expected to commence within 7 days." },
    ],
  },
  {
    id: 14,
    property: "Cwmdu Industrial Estate",
    location: "Swansea",
    type: "Industrial",
    size: "5,800",
    sizeSqft: 5800,
    asking: "£29,000 pa",
    daysOnMarket: 44,
    enquiries: 4,
    viewings: 2,
    status: "Available",
    fullAddress: "Unit 6, Cwmdu Industrial Estate, Cwmdu Road, Swansea, SA5 8JF",
    tenure: "Leasehold",
    epc: "D",
    availableFrom: "Immediate",
    description: "Established industrial unit on the well-known Cwmdu Estate in west Swansea, providing practical warehouse accommodation with a ground-level roller shutter door, 6m eaves, and a single-storey office and welfare block to the front. The unit is suitable for light industrial, trade counter, or storage and distribution uses and benefits from reasonable proximity to the M4 at Junction 47.",
    landlordName: "Cwmdu Estates Ltd",
    landlordContact: "Mr H. Walters - 01792 585 100",
    agentInitials: "DB",
    parkingSpaces: 8,
    rateable: "£19,500",
    dealIds: [],
    activity: [
      { date: "2026-01-19", type: "marketing", text: "Unit listed on CoStar and local industrial property network following tenant departure.", agent: "DB" },
      { date: "2026-01-26", type: "enquiry", text: "Enquiry from a plumbing and heating merchant.", agent: "DB" },
      { date: "2026-02-02", type: "enquiry", text: "Enquiry from a vehicle servicing and MOT operation.", agent: "DB" },
      { date: "2026-02-10", type: "viewing", text: "Viewing with plumbing merchant - needs to assess drainage and water supply infrastructure.", agent: "DB", detail: "Awaiting landlord confirmation of drainage spec." },
      { date: "2026-02-20", type: "viewing", text: "Viewing with vehicle servicing operator - strong interest.", agent: "DB" },
      { date: "2026-03-01", type: "note", text: "Follow-up call to vehicle servicing operator - reviewing planning position for change of use. Decision expected in 2 weeks.", agent: "DB" },
    ],
  },
  {
    id: 15,
    property: "Milland Road",
    location: "Neath",
    type: "Industrial",
    size: "22,000",
    sizeSqft: 22000,
    asking: "£1,200,000 fh",
    daysOnMarket: 61,
    enquiries: 3,
    viewings: 2,
    status: "Stc",
    fullAddress: "Milland Road Industrial Estate, Milland Road, Neath, SA11 1NJ",
    tenure: "Freehold",
    epc: "D",
    availableFrom: "STC",
    description: "Significant freehold industrial complex for sale by way of sale and leaseback or vacant possession, comprising three interconnected warehouse buildings with a total of 22,000 sqft. The site extends to approximately 1.8 acres with a large secure yard, and benefits from good access to the A465 Heads of the Valleys Road and the M4 via the A48. Subject to contract following a competitive best-and-final process.",
    landlordName: "Milland Road Properties Ltd",
    landlordContact: "Mr F. Prosser - 01639 771 400",
    agentInitials: "RJ",
    parkingSpaces: 25,
    rateable: "£72,000",
    dealIds: ["e2"],
    activity: [
      { date: "2026-01-01", type: "marketing", text: "Freehold brought to market via private treaty. Brochure issued to pre-qualified industrial investors and owner-occupiers.", agent: "RJ" },
      { date: "2026-01-10", type: "enquiry", text: "Enquiry from a private equity-backed industrial investor.", agent: "RJ", detail: "Requested 3-year financial track record and tenancy schedule." },
      { date: "2026-01-20", type: "enquiry", text: "Enquiry from a Welsh manufacturing group seeking owner-occupier acquisition.", agent: "RJ" },
      { date: "2026-01-28", type: "viewing", text: "Viewing with private equity investor and their surveyor.", agent: "RJ" },
      { date: "2026-02-05", type: "viewing", text: "Viewing with Welsh manufacturing group - two directors attended.", agent: "RJ", detail: "Very positive. Considering sale-and-leaseback structure." },
      { date: "2026-02-14", type: "offer", text: "Best-and-final offers received. Offer from manufacturing group of £1,175,000 accepted.", agent: "RJ", detail: "Heads of Terms issued. Solicitors instructed on both sides. Structural survey commissioned." },
      { date: "2026-02-28", type: "status_change", text: "Status updated to STC. Subject to satisfactory survey and searches.", agent: "RJ" },
    ],
  },
  {
    id: 16,
    property: "Treforest Industrial Estate",
    location: "Treforest",
    type: "Industrial",
    size: "11,400",
    sizeSqft: 11400,
    asking: "£57,000 pa",
    daysOnMarket: 9,
    enquiries: 6,
    viewings: 3,
    status: "Available",
    fullAddress: "Unit 4, Treforest Industrial Estate, Pontypridd Road, Treforest, CF37 5YL",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Immediate",
    description: "Well-specified modern industrial unit on one of Wales' most established industrial estates, with immediate access to the A470 and the M4 corridor at Junction 32. The building provides a clear-span warehouse with 8.5m eaves, two dock-level and one ground-level loading doors, integral two-storey offices, and a fenced and gated yard. The estate benefits from on-site management and security.",
    landlordName: "Treforest Estate Management Ltd",
    landlordContact: "Mr G. Price - 01443 841 600",
    agentInitials: "RJ",
    parkingSpaces: 18,
    rateable: "£38,000",
    dealIds: [],
    activity: [
      { date: "2026-02-23", type: "marketing", text: "Unit newly available. Launched on CoStar, JLL Industrial Network, and Treforest Estate occupier mailing list.", agent: "RJ" },
      { date: "2026-02-25", type: "enquiry", text: "Enquiry from a Midlands-based e-commerce operator seeking a South Wales fulfilment hub.", agent: "RJ", detail: "Urgent requirement - aim to be operational by June 2026." },
      { date: "2026-02-26", type: "enquiry", text: "Enquiry from a food manufacturing company exploring capacity expansion.", agent: "RJ" },
      { date: "2026-02-27", type: "enquiry", text: "Enquiry from a national parcel carrier seeking a depot location.", agent: "RJ" },
      { date: "2026-03-01", type: "viewing", text: "Viewing with e-commerce operator - head of operations attended, very urgent.", agent: "RJ", detail: "Lease terms discussed. Requesting heads of terms." },
      { date: "2026-03-02", type: "viewing", text: "Viewing with food manufacturer - EHO officer to assess ventilation before commitment.", agent: "RJ" },
      { date: "2026-03-03", type: "viewing", text: "Viewing with national parcel carrier - surveyor and depot operations manager.", agent: "RJ" },
    ],
  },
  {
    id: 17,
    property: "Swansea Vale Business Park",
    location: "Swansea",
    type: "Industrial",
    size: "6,200",
    sizeSqft: 6200,
    asking: "£31,000 pa",
    daysOnMarket: 76,
    enquiries: 2,
    viewings: 1,
    status: "Available",
    fullAddress: "Unit 9, Swansea Vale Business Park, Phoenix Way, Swansea, SA7 9LG",
    tenure: "Leasehold",
    epc: "E",
    availableFrom: "Immediate",
    description: "Mid-terrace industrial unit on the established Swansea Vale Business Park, offering clear-span warehouse with 5.5m eaves, a single roller shutter loading door, and a ground-floor office and welfare block. The unit has been on the market for some time and the landlord is open to discussing an improved incentive package for the right occupier. Suitable for storage, light manufacturing, or trade counter use.",
    landlordName: "Swansea Vale Estates Ltd",
    landlordContact: "Mr O. Hughes - 01792 780 900",
    agentInitials: "DB",
    parkingSpaces: 7,
    rateable: "£21,000",
    dealIds: [],
    activity: [
      { date: "2025-12-17", type: "marketing", text: "Unit listed on CoStar and local industrial network. Rent reduction from £34,000 to £31,000 agreed with landlord.", agent: "DB" },
      { date: "2026-01-08", type: "enquiry", text: "Enquiry from a sole-trader builder's merchant - below budget after rent reduction.", agent: "DB" },
      { date: "2026-01-20", type: "viewing", text: "Viewing with a small timber fabrication company - eaves height insufficient for their requirements.", agent: "DB", detail: "Feedback noted. Will look at alternative units with higher eaves." },
      { date: "2026-02-14", type: "note", text: "Landlord agreed to offer 3 months rent-free on any lease over 3 years. Instructions updated.", agent: "DB" },
      { date: "2026-03-01", type: "note", text: "Unit remains available. Refreshed marketing campaign planned for April. DB to review strategy.", agent: "DB" },
    ],
  },
  {
    id: 18,
    property: "Bridgend Trade Park, Unit 4",
    location: "Bridgend",
    type: "Trade Counter",
    size: "3,100",
    sizeSqft: 3100,
    asking: "£24,000 pa",
    daysOnMarket: 27,
    enquiries: 8,
    viewings: 4,
    status: "Available",
    fullAddress: "Unit 4, Bridgend Trade Park, Coychurch Road, Bridgend, CF35 5LJ",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Immediate",
    description: "Modern trade counter unit on the popular Bridgend Trade Park, offering a wide frontage with glazed showroom/customer area to the front and clear-span warehouse to the rear. The unit benefits from excellent visibility from Coychurch Road and has immediate neighbours including Toolstation and Screwfix. Suitable for trade and builder's merchants, plumbing and heating suppliers, or similar trade-facing operations.",
    landlordName: "Bridgend Trade Park Estates Ltd",
    landlordContact: "Ms L. Edwards - 01656 643 900",
    agentInitials: "MW",
    parkingSpaces: 10,
    rateable: "£16,500",
    dealIds: [],
    activity: [
      { date: "2026-02-05", type: "marketing", text: "Unit listed on CoStar Trade Counter Database. Approached 35 trade counter operators active in South Wales.", agent: "MW" },
      { date: "2026-02-10", type: "enquiry", text: "Enquiry from a national electrical wholesaler.", agent: "MW", detail: "Seeking a Bridgend presence to complement existing Cardiff and Swansea branches." },
      { date: "2026-02-13", type: "enquiry", text: "Enquiry from a regional plumbing and heating specialist.", agent: "MW" },
      { date: "2026-02-16", type: "viewing", text: "Viewing with electrical wholesaler - very positive.", agent: "MW", detail: "Head of property and area manager attended. Requesting lease terms." },
      { date: "2026-02-19", type: "enquiry", text: "Enquiry from a flooring supplies company.", agent: "MW" },
      { date: "2026-02-22", type: "viewing", text: "Viewing with plumbing and heating specialist - measuring for counter layout.", agent: "MW" },
      { date: "2026-02-26", type: "viewing", text: "Viewing with flooring company - positive, second visit being arranged.", agent: "MW" },
      { date: "2026-03-03", type: "viewing", text: "Second viewing with electrical wholesaler - board sign-off pending. Offer expected this week.", agent: "MW" },
    ],
  },
  {
    id: 19,
    property: "Fabian Way Trade Centre",
    location: "Swansea",
    type: "Trade Counter",
    size: "4,800",
    sizeSqft: 4800,
    asking: "£36,000 pa",
    daysOnMarket: 15,
    enquiries: 10,
    viewings: 5,
    status: "Available",
    fullAddress: "Unit 3, Fabian Way Trade Centre, Fabian Way, Port Tennant, Swansea, SA1 8QB",
    tenure: "Leasehold",
    epc: "B",
    availableFrom: "Immediate",
    description: "Prominent and recently refurbished trade counter unit on the busy Fabian Way corridor in east Swansea, one of South Wales' busiest trade and industrial arterial routes. The unit offers an impressive frontage with showroom, rear warehouse with dock-level loading, and a mezzanine storage deck. Immediately adjacent occupiers include Travis Perkins and Howdens Joinery. High volume of passing trade.",
    landlordName: "Fabian Way Trade Investments Ltd",
    landlordContact: "Mr N. Rossiter - 01792 460 830",
    agentInitials: "DB",
    parkingSpaces: 16,
    rateable: "£24,000",
    dealIds: [],
    activity: [
      { date: "2026-02-17", type: "marketing", text: "Refurbished unit launched to market. Premium CoStar profile placed and full trade counter circular issued.", agent: "DB" },
      { date: "2026-02-18", type: "enquiry", text: "Enquiry from a national builders merchant chain.", agent: "DB", detail: "Already present on Fabian Way - interested in unit as second premises or relocation." },
      { date: "2026-02-19", type: "enquiry", text: "Enquiry from a bathroom and kitchen showroom group.", agent: "DB" },
      { date: "2026-02-20", type: "enquiry", text: "Enquiry from a regional electrical wholesale company.", agent: "DB" },
      { date: "2026-02-21", type: "viewing", text: "Viewing with builders merchant chain - head of property and surveyor.", agent: "DB", detail: "Very interested in the dock-level loading. Measuring up for racking layout." },
      { date: "2026-02-24", type: "viewing", text: "Viewing with bathroom and kitchen showroom group - two directors.", agent: "DB" },
      { date: "2026-02-27", type: "viewing", text: "Viewing with electrical wholesale company.", agent: "DB" },
      { date: "2026-03-01", type: "viewing", text: "Second viewing with builders merchant - offer discussion expected.", agent: "DB" },
    ],
  },
  {
    id: 20,
    property: "Newport Trade Park",
    location: "Newport",
    type: "Trade Counter",
    size: "2,600",
    sizeSqft: 2600,
    asking: "£21,000 pa",
    daysOnMarket: 38,
    enquiries: 5,
    viewings: 2,
    status: "Let Agreed",
    fullAddress: "Unit 7, Newport Trade Park, Stephenson Street, Newport, NP19 4XH",
    tenure: "Leasehold",
    epc: "C",
    availableFrom: "Let Agreed",
    description: "Compact trade counter unit within the well-established Newport Trade Park, adjacent to the city centre and with good access to the M4 at Junction 28. Let agreed to a national tools and fixings distributor on a new 5-year lease. The unit provides a customer-facing showroom area to the front and a clear-span warehouse to the rear with single roller shutter loading.",
    landlordName: "Newport Commercial Properties Ltd",
    landlordContact: "Mr K. Watkins - 01633 780 440",
    agentInitials: "MW",
    parkingSpaces: 8,
    rateable: "£14,000",
    dealIds: [],
    activity: [
      { date: "2026-01-25", type: "marketing", text: "Unit listed on CoStar and Newport Commercial database. Targeted mailing to trade counter operators.", agent: "MW" },
      { date: "2026-01-31", type: "enquiry", text: "Enquiry from a national fixings and fasteners distributor.", agent: "MW", detail: "Actively seeking a Newport location. Existing branch in Cardiff." },
      { date: "2026-02-05", type: "enquiry", text: "Enquiry from a regional paint and decorating supplies company.", agent: "MW" },
      { date: "2026-02-10", type: "viewing", text: "Viewing with fixings distributor - area manager and property surveyor attended.", agent: "MW", detail: "Very positive. Board approval needed." },
      { date: "2026-02-17", type: "viewing", text: "Viewing with paint supplies company - also looking at nearby alternative.", agent: "MW" },
      { date: "2026-02-23", type: "offer", text: "Offer from national fixings distributor at £20,500 pa on a 5-year lease. Accepted by landlord.", agent: "MW", detail: "Heads of Terms signed. Solicitors instructed." },
      { date: "2026-03-03", type: "status_change", text: "Let Agreed - exchange of contracts completed. Tenant to commence fit-out 1 April 2026.", agent: "MW" },
    ],
  },
  {
    id: 21,
    property: "Kingsway (Ground Floor)",
    location: "Swansea",
    type: "Leisure",
    size: "2,200",
    sizeSqft: 2200,
    asking: "£38,000 pa",
    daysOnMarket: 55,
    enquiries: 3,
    viewings: 2,
    status: "Available",
    fullAddress: "Ground Floor, 70 Kingsway, Swansea City Centre, Swansea, SA1 5HX",
    tenure: "Leasehold",
    epc: "D",
    availableFrom: "Immediate",
    description: "Substantial ground-floor leisure unit on the Kingsway with prominent glazed frontage and excellent passing trade from office workers, shoppers, and the adjacent Wind Street entertainment quarter. The unit benefits from an existing catering extraction system, a commercial kitchen prep area, and a WC core. Well-suited to a bar, restaurant, café, or fitness and wellness operator. Class E/Sui Generis permission in place.",
    landlordName: "Kingsway Leisure Properties Ltd",
    landlordContact: "Mr P. Stead - 01792 630 200",
    agentInitials: "DB",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£24,000",
    dealIds: [],
    activity: [
      { date: "2026-01-08", type: "marketing", text: "Unit relaunched to market following previous tenant exit. Positioned as leisure/F&B opportunity on Kingsway.", agent: "DB" },
      { date: "2026-01-19", type: "enquiry", text: "Enquiry from a branded burger and wings franchise.", agent: "DB", detail: "Strong national covenant. Requesting planning confirmation for A5 use." },
      { date: "2026-01-30", type: "enquiry", text: "Enquiry from a yoga and pilates studio group.", agent: "DB" },
      { date: "2026-02-06", type: "viewing", text: "Viewing with burger franchise - area manager and surveyors.", agent: "DB", detail: "Interested in the extraction infrastructure. Requested structural survey." },
      { date: "2026-02-20", type: "viewing", text: "Viewing with yoga studio group - measuring for class studio layout.", agent: "DB" },
      { date: "2026-03-01", type: "enquiry", text: "Enquiry from an independent cocktail bar operator.", agent: "DB" },
    ],
  },
  {
    id: 22,
    property: "Wind Street Units",
    location: "Swansea",
    type: "Leisure",
    size: "1,650",
    sizeSqft: 1650,
    asking: "£32,500 pa",
    daysOnMarket: 42,
    enquiries: 6,
    viewings: 3,
    status: "Under Offer",
    fullAddress: "Units 4–5 Wind Street, Swansea City Centre, Swansea, SA1 1DP",
    tenure: "Leasehold",
    epc: "D",
    availableFrom: "Under Offer",
    description: "Paired ground-floor leisure units on Wind Street - Swansea's most active bar and restaurant street - now being marketed as a single combined letting. The combined unit benefits from A3/A4 permission, existing bar infrastructure, and a prominent double frontage. Under offer to a well-funded independent bar and kitchen operator looking to establish a flagship Swansea venue.",
    landlordName: "Wind Street Estates Ltd",
    landlordContact: "Ms H. Price - 01792 490 810",
    agentInitials: "DB",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£21,000",
    dealIds: ["u1"],
    activity: [
      { date: "2026-01-21", type: "marketing", text: "Units relisted on Wind Street following combined marketing strategy decision. F&B and leisure operators directly approached.", agent: "DB" },
      { date: "2026-01-28", type: "enquiry", text: "Enquiry from a cocktail bar group with venues in Cardiff and Bristol.", agent: "DB", detail: "Keen on the double frontage and Wind Street provenance. Reviewing financials." },
      { date: "2026-02-03", type: "enquiry", text: "Enquiry from a live music bar operator.", agent: "DB" },
      { date: "2026-02-10", type: "viewing", text: "Viewing with cocktail bar group - two founding directors and their architect.", agent: "DB", detail: "Very positive. Architect measured for full site survey." },
      { date: "2026-02-17", type: "viewing", text: "Viewing with live music bar operator - strong interest.", agent: "DB" },
      { date: "2026-02-24", type: "offer", text: "Formal offer received from cocktail bar group at £31,000 pa on a 10-year lease with 5-year break. Accepted by landlord.", agent: "DB", detail: "Heads of Terms issued. Solicitors instructed on both sides." },
      { date: "2026-03-01", type: "status_change", text: "Status updated to Under Offer. Property withdrawn from active marketing.", agent: "DB" },
    ],
  },
  {
    id: 23,
    property: "Cardiff Bay, Mermaid Quay",
    location: "Cardiff",
    type: "Leisure",
    size: "3,400",
    sizeSqft: 3400,
    asking: "£67,000 pa",
    daysOnMarket: 17,
    enquiries: 9,
    viewings: 5,
    status: "Available",
    fullAddress: "Unit 12 Mermaid Quay, Cardiff Bay Retail and Leisure Park, Cardiff, CF10 5BZ",
    tenure: "Leasehold",
    epc: "B",
    availableFrom: "Immediate",
    description: "Premium waterfront leisure unit on the iconic Mermaid Quay development in Cardiff Bay, offering stunning views over the bay and Roald Dahl Plass. The unit benefits from an A3 restaurant use permission, a full commercial kitchen, and a south-facing licensed terrace. Adjacent operators include established national brands and the unit enjoys one of the highest footfall locations in Wales, bolstered by the nearby Wales Millennium Centre and Senedd.",
    landlordName: "Cardiff Bay Waterfront Properties plc",
    landlordContact: "Mr S. Hennessey - 029 2046 9900",
    agentInitials: "RJ",
    floorLevel: "Ground Floor",
    parkingSpaces: 0,
    rateable: "£44,500",
    dealIds: [],
    activity: [
      { date: "2026-02-15", type: "marketing", text: "Premium marketing campaign launched - CoStar Premium placement, targeted approach to 60 national restaurant and leisure groups.", agent: "RJ" },
      { date: "2026-02-17", type: "enquiry", text: "Enquiry from a national Japanese restaurant chain.", agent: "RJ", detail: "Strong national covenant. Cardiff Bay on their target location list." },
      { date: "2026-02-18", type: "enquiry", text: "Enquiry from a premium casual dining group with 12 sites across England and Wales.", agent: "RJ" },
      { date: "2026-02-19", type: "enquiry", text: "Enquiry from a waterside cocktail bar and grill brand.", agent: "RJ" },
      { date: "2026-02-21", type: "viewing", text: "Viewing with Japanese restaurant chain - area manager and head of property.", agent: "RJ", detail: "Terrace viewed positively. Requesting planning confirmation for external works." },
      { date: "2026-02-23", type: "viewing", text: "Viewing with casual dining group - operations director and kitchen designer attended.", agent: "RJ" },
      { date: "2026-02-26", type: "viewing", text: "Viewing with cocktail bar brand - three representatives.", agent: "RJ" },
      { date: "2026-03-01", type: "viewing", text: "Viewing with a Welsh-themed dining concept backed by a Cardiff-based restaurant group.", agent: "RJ" },
    ],
  },
]
