import type { Assessment, AssessmentMetricOutput, AssessmentNutrientOutput } from "./types";

export const assessments: Assessment[] = [
  {
    id: "ASM-001",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    assessorId: "A-001",
    assessorName: "Sarah Chen",
    type: "NN Baseline",
    date: "2025-05-20",
    status: "Approved",
    findings: "Arable land with moderate nitrogen loading from historic fertiliser use. Conversion to permanent grassland with buffer strips along watercourse will significantly reduce nutrient runoff to the Solent. Soil samples confirm clay loam substrate with good retention properties. Recommended 10m riparian buffer along southern boundary.",
    creditYield: 95,
    creditYieldLabel: "95 kg/yr nitrogen credits",
    habitatTypes: ["Arable", "Improved grassland", "Riparian buffer"],
    conditionScore: 3.2,
    reportDocId: "DOC-009",
    nutrientOutput: {
      baselineLoadingKgYr: 340,
      proposedLoadingKgYr: 245,
      creditYieldKgYr: 95,
      loadingFactorBaseline: 5.67,
      loadingFactorProposed: 4.08,
      landUseChange: "Arable → Permanent Grassland + Riparian Buffer Strips",
    },
  },
  {
    id: "ASM-002",
    siteRef: "S-0002",
    siteName: "Botley Meadows",
    assessorId: "A-001",
    assessorName: "Sarah Chen",
    type: "NN Baseline",
    date: "2025-03-15",
    status: "Approved",
    findings: "Large pastoral site with existing low-intensity grazing. Alluvial clay soils show good nutrient retention. Proposed conversion from dairy pasture to extensive grassland with wildflower margins will reduce nitrogen loading substantially. Site benefits from natural wetland features along the River Hamble corridor.",
    creditYield: 120,
    creditYieldLabel: "120 kg/yr nitrogen credits",
    habitatTypes: ["Improved grassland", "Semi-improved grassland", "Wetland margin"],
    conditionScore: 4.1,
    reportDocId: "DOC-010",
    nutrientOutput: {
      baselineLoadingKgYr: 425,
      proposedLoadingKgYr: 305,
      creditYieldKgYr: 120,
      loadingFactorBaseline: 5.0,
      loadingFactorProposed: 3.59,
      landUseChange: "Dairy Pasture → Extensive Grassland + Wetland Margins",
    },
  },
  {
    id: "ASM-003",
    siteRef: "S-0003",
    siteName: "Hamble Valley",
    assessorId: "A-004",
    assessorName: "Tom Briggs",
    type: "NN Baseline",
    date: "2024-10-08",
    status: "Approved",
    findings: "Mixed grazing land on sandy loam. Moderate baseline loading from livestock. Conversion to hay meadow management with reduced stocking density. Site includes existing hedgerow network providing additional ecological benefit.",
    creditYield: 80,
    creditYieldLabel: "80 kg/yr nitrogen credits",
    habitatTypes: ["Mixed grazing", "Hedgerow", "Hay meadow"],
    conditionScore: 3.5,
    nutrientOutput: {
      baselineLoadingKgYr: 180,
      proposedLoadingKgYr: 100,
      creditYieldKgYr: 80,
      loadingFactorBaseline: 4.0,
      loadingFactorProposed: 2.22,
      landUseChange: "Mixed Grazing → Hay Meadow, Reduced Stocking Density",
    },
  },
  {
    id: "ASM-004",
    siteRef: "S-0005",
    siteName: "Manor Fields",
    assessorId: "A-002",
    assessorName: "David Park",
    type: "NN Baseline",
    date: "2025-07-12",
    status: "Approved",
    findings: "Arable site on chalk over clay substrate. High baseline nitrogen loading from intensive cereal production. Proposed conversion to species-rich chalk grassland will deliver significant nutrient reduction. Strategic location between two existing mitigation sites creates corridor benefit.",
    creditYield: 95,
    creditYieldLabel: "95 kg/yr nitrogen credits",
    habitatTypes: ["Arable", "Chalk grassland"],
    conditionScore: 2.8,
    nutrientOutput: {
      baselineLoadingKgYr: 330,
      proposedLoadingKgYr: 235,
      creditYieldKgYr: 95,
      loadingFactorBaseline: 6.0,
      loadingFactorProposed: 4.27,
      landUseChange: "Arable → Species-rich Chalk Grassland",
    },
  },
  {
    id: "ASM-005",
    siteRef: "S-0006",
    siteName: "Test Valley Grassland",
    assessorId: "A-005",
    assessorName: "Lisa Grant",
    type: "NN Baseline",
    date: "2025-12-10",
    status: "Approved",
    findings: "Large pastoral site in the Test Valley catchment. Chalk grassland substrate with naturally low background loading. However, intensive dairy use has elevated nitrogen significantly. Conversion to extensive grazing with buffer zones along chalk streams will deliver substantial credit yield.",
    creditYield: 165,
    creditYieldLabel: "165 kg/yr nitrogen credits",
    habitatTypes: ["Improved grassland", "Chalk stream buffer", "Wildflower meadow"],
    conditionScore: 3.8,
    nutrientOutput: {
      baselineLoadingKgYr: 550,
      proposedLoadingKgYr: 385,
      creditYieldKgYr: 165,
      loadingFactorBaseline: 5.0,
      loadingFactorProposed: 3.5,
      landUseChange: "Intensive Dairy → Extensive Grazing + Chalk Stream Buffers",
    },
  },
  {
    id: "ASM-006",
    siteRef: "S-0008",
    siteName: "Fareham Woodland",
    assessorId: "A-002",
    assessorName: "David Park",
    type: "BNG Habitat Survey",
    date: "2026-02-05",
    status: "Approved",
    findings: "Existing secondary woodland with modified understorey. Baseline biodiversity units calculated using Metric 4.0. Proposed management: thinning of canopy to increase light penetration, removal of invasive species (cherry laurel, rhododendron), and creation of woodland edge habitat. Will deliver significant net gain.",
    creditYield: 22.5,
    creditYieldLabel: "22.5 biodiversity units",
    habitatTypes: ["Broadleaved woodland", "Woodland edge", "Scrub mosaic"],
    conditionScore: 4.5,
    reportDocId: "DOC-010",
    metricOutput: {
      metricVersion: "Statutory Metric 1.0",
      calculationDate: "2026-02-05",
      baselineParcels: [
        {
          id: "BP-001", phase: "baseline", category: "area",
          broadHabitatType: "Woodland", specificHabitatType: "Woodland and Forest; Conifer Plantation",
          distinctiveness: "low", distinctivenessScore: 2, condition: "poor", conditionScore: 1.0,
          strategicSignificance: "low", significanceMultiplier: 1.0,
          parcelCount: 3, size: 11.0, sizeUnit: "ha", biodiversityUnits: 33.0,
          unitGain: null, allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: 0.0, temporalRisk: null, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "BP-002", phase: "baseline", category: "area",
          broadHabitatType: "Scrub", specificHabitatType: "Scrub",
          distinctiveness: "medium", distinctivenessScore: 4, condition: "poor", conditionScore: 1.0,
          strategicSignificance: "low", significanceMultiplier: 1.0,
          parcelCount: 2, size: 4.5, sizeUnit: "ha", biodiversityUnits: 18.0,
          unitGain: null, allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: 0.0, temporalRisk: null, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "BP-003", phase: "baseline", category: "area",
          broadHabitatType: "Scrub", specificHabitatType: "Bramble Scrub",
          distinctiveness: "medium", distinctivenessScore: 4, condition: "poor", conditionScore: 1.0,
          strategicSignificance: "low", significanceMultiplier: 1.0,
          parcelCount: 1, size: 1.5, sizeUnit: "ha", biodiversityUnits: 6.0,
          unitGain: null, allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: 0.0, temporalRisk: null, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "BP-004", phase: "baseline", category: "area",
          broadHabitatType: "Grassland", specificHabitatType: "Modified Grassland",
          distinctiveness: "low", distinctivenessScore: 2, condition: "poor", conditionScore: 1.0,
          strategicSignificance: "low", significanceMultiplier: 1.0,
          parcelCount: 2, size: 1.0, sizeUnit: "ha", biodiversityUnits: 2.0,
          unitGain: null, allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: 0.0, temporalRisk: null, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "BP-005", phase: "baseline", category: "hedgerow",
          broadHabitatType: "Hedgerow", specificHabitatType: "Hedgerow; No Associated Trees",
          distinctiveness: "low", distinctivenessScore: 2, condition: "poor", conditionScore: 1.0,
          strategicSignificance: "low", significanceMultiplier: 1.0,
          parcelCount: 1, size: 0.6, sizeUnit: "km", biodiversityUnits: 1.2,
          unitGain: null, allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: 0.6, temporalRisk: null, spatialRisk: null, difficultyMultiplier: null,
        },
      ],
      improvementParcels: [
        {
          id: "IP-001", phase: "improvement", category: "area",
          broadHabitatType: "Woodland", specificHabitatType: "Lowland Mixed Deciduous Woodland",
          distinctiveness: "v_high", distinctivenessScore: 8, condition: "moderate", conditionScore: 2.0,
          strategicSignificance: "medium", significanceMultiplier: 1.1,
          parcelCount: 3, size: 11.0, sizeUnit: "ha", biodiversityUnits: 145.2, unitGain: 112.2,
          allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: null, temporalRisk: 0.75, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "IP-002", phase: "improvement", category: "area",
          broadHabitatType: "Woodland", specificHabitatType: "Woodland Edge",
          distinctiveness: "medium", distinctivenessScore: 4, condition: "fairly_good", conditionScore: 2.5,
          strategicSignificance: "medium", significanceMultiplier: 1.1,
          parcelCount: 2, size: 4.5, sizeUnit: "ha", biodiversityUnits: 42.1, unitGain: 24.1,
          allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: null, temporalRisk: 0.85, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "IP-003", phase: "improvement", category: "area",
          broadHabitatType: "Scrub", specificHabitatType: "Scrub Mosaic (Mixed Scrub)",
          distinctiveness: "medium", distinctivenessScore: 4, condition: "moderate", conditionScore: 2.0,
          strategicSignificance: "low", significanceMultiplier: 1.0,
          parcelCount: 2, size: 1.5, sizeUnit: "ha", biodiversityUnits: 10.8, unitGain: null,
          allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: null, temporalRisk: 0.90, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "IP-004", phase: "improvement", category: "area",
          broadHabitatType: "Grassland", specificHabitatType: "Species-rich Neutral Grassland",
          distinctiveness: "medium", distinctivenessScore: 4, condition: "moderate", conditionScore: 2.0,
          strategicSignificance: "medium", significanceMultiplier: 1.1,
          parcelCount: 1, size: 1.0, sizeUnit: "ha", biodiversityUnits: 7.9, unitGain: null,
          allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: null, temporalRisk: 0.90, spatialRisk: null, difficultyMultiplier: null,
        },
        {
          id: "IP-005", phase: "improvement", category: "hedgerow",
          broadHabitatType: "Hedgerow", specificHabitatType: "Hedgerow; Native Species-rich",
          distinctiveness: "high", distinctivenessScore: 6, condition: "moderate", conditionScore: 2.0,
          strategicSignificance: "medium", significanceMultiplier: 1.1,
          parcelCount: 2, size: 1.2, sizeUnit: "km", biodiversityUnits: 13.5, unitGain: 12.3,
          allocatedSize: 0, allocatedPercent: 0, allocatedUnits: 0,
          retainedSize: null, temporalRisk: 0.85, spatialRisk: null, difficultyMultiplier: null,
        },
      ],
      totalBaselineHUs: 59.0,
      totalImprovementHUs: 206.0,
      totalHUGain: 147.0,
      hedgerowBaselineHUs: 1.2,
      hedgerowImprovementHUs: 13.5,
      hedgerowHUGain: 12.3,
    } satisfies AssessmentMetricOutput,
  },
  {
    id: "ASM-007",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    assessorId: "A-003",
    assessorName: "Emma Walsh",
    type: "Annual Monitoring",
    date: "2026-03-25",
    status: "Scheduled",
    findings: undefined,
  },
  {
    id: "ASM-008",
    siteRef: "S-0002",
    siteName: "Botley Meadows",
    assessorId: "A-003",
    assessorName: "Emma Walsh",
    type: "Annual Monitoring",
    date: "2026-04-02",
    status: "Scheduled",
    findings: undefined,
  },
];
