import type { ComplianceItem } from "./types";

export const complianceItems: ComplianceItem[] = [
  // ── Overdue (3) ──
  {
    id: "CMP-001",
    title: "Annual Monitoring Report - Whiteley Farm",
    category: "Monitoring",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    dueDate: "2026-02-28",
    status: "Overdue",
    assigned: "Emma Walsh",
    assignedInitials: "EW",
    frequency: "Annual",
    description: "Annual nutrient monitoring report required under S106 agreement. Includes water quality sampling, vegetation survey, and photo evidence of land management compliance.",
  },
  {
    id: "CMP-002",
    title: "Water Quality Sampling - Botley Meadows",
    category: "Monitoring",
    siteRef: "S-0002",
    siteName: "Botley Meadows",
    dueDate: "2026-02-15",
    status: "Overdue",
    assigned: "Emma Walsh",
    assignedInitials: "EW",
    frequency: "Quarterly",
    description: "Quarterly water quality sampling at three monitoring points along southern boundary drain. Required under S106 clause 14.2.",
  },
  {
    id: "CMP-003",
    title: "LPA Annual Return - Hamble Valley",
    category: "Registration",
    siteRef: "S-0003",
    siteName: "Hamble Valley",
    dueDate: "2026-03-01",
    status: "Overdue",
    assigned: "James Harris",
    assignedInitials: "JH",
    frequency: "Annual",
    description: "Annual compliance return to Eastleigh Borough Council confirming ongoing mitigation delivery and credit allocation status.",
  },
  {
    id: "CMP-011",
    title: "Habitat Management Plan Review — Hamble Valley",
    category: "Management",
    siteRef: "S-0003",
    siteName: "Hamble Valley",
    dueDate: "2026-02-01",
    status: "Overdue",
    assigned: "Tom Jenkins",
    assignedInitials: "TJ",
    frequency: "Annual",
    description: "Annual review of habitat management plan required under BNG condition. Includes evidence of scrub management, hedge laying schedule, and grazing records.",
  },
  {
    id: "CMP-012",
    title: "Phosphorus Monitoring Report — Test Valley Grassland",
    category: "Monitoring",
    siteRef: "S-0006",
    siteName: "Test Valley Grassland",
    dueDate: "2026-01-31",
    status: "Overdue",
    assigned: "Emma Walsh",
    assignedInitials: "EW",
    frequency: "Quarterly",
    description: "Quarterly phosphorus load monitoring at two river sample points. Required under Test Valley catchment nutrient neutrality protocol.",
  },
  {
    id: "CMP-013",
    title: "BNG Credit Certificate Renewal — Fareham Woodland",
    category: "Certification",
    siteRef: "S-0008",
    siteName: "Fareham Woodland",
    dueDate: "2026-02-10",
    status: "Overdue",
    assigned: "Sarah Croft",
    assignedInitials: "SC",
    frequency: "Annual",
    description: "Annual renewal of biodiversity net gain credit certificates with Natural England. BGS reference numbers must be confirmed before credits can be traded.",
  },
  {
    id: "CMP-014",
    title: "Landowner Consent Confirmation — Manor Fields",
    category: "Legal",
    siteRef: "S-0005",
    siteName: "Manor Fields",
    dueDate: "2026-02-20",
    status: "Overdue",
    assigned: "James Harris",
    assignedInitials: "JH",
    frequency: "One-off",
    description: "Signed landowner consent letter required ahead of credit allocation to Persimmon phase 2. Solicitor confirmed delay due to probate proceedings.",
  },
  // ── Due Soon (2) ──
  {
    id: "CMP-004",
    title: "Insurance Renewal - Whiteley Farm",
    category: "Financial",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    dueDate: "2026-03-12",
    status: "Due Soon",
    assigned: "Sarah Croft",
    assignedInitials: "SC",
    frequency: "Annual",
    description: "Professional indemnity and public liability insurance renewal for mitigation site operations.",
  },
  {
    id: "CMP-005",
    title: "HMMP Submission - Fareham Woodland",
    category: "Legal",
    siteRef: "S-0008",
    siteName: "Fareham Woodland",
    dueDate: "2026-03-15",
    status: "Due Soon",
    assigned: "David Park",
    assignedInitials: "DP",
    frequency: "One-off",
    description: "Habitat Management & Monitoring Plan must be submitted to Natural England as part of BNG gain site registration. 30-year management plan required.",
  },
  // ── Upcoming (5) ──
  {
    id: "CMP-006",
    title: "Quarterly Monitoring Visit - Manor Fields",
    category: "Monitoring",
    siteRef: "S-0005",
    siteName: "Manor Fields",
    dueDate: "2026-04-01",
    status: "Upcoming",
    assigned: "Emma Walsh",
    assignedInitials: "EW",
    frequency: "Quarterly",
    description: "Routine quarterly site visit to check grassland conversion progress and fence line integrity.",
  },
  {
    id: "CMP-007",
    title: "Credit Allocation Confirmation - D-0030",
    category: "Registration",
    dealRef: "D-0030",
    dealTitle: "Bellway / Whiteley Farm",
    dueDate: "2026-04-15",
    status: "Upcoming",
    assigned: "James Harris",
    assignedInitials: "JH",
    frequency: "One-off",
    description: "Confirm credit allocation with Natural England register following contract completion and payment receipt.",
  },
  {
    id: "CMP-008",
    title: "5-Year Review - Botley Meadows",
    category: "Monitoring",
    siteRef: "S-0002",
    siteName: "Botley Meadows",
    dueDate: "2026-04-22",
    status: "Upcoming",
    assigned: "Sarah Chen",
    assignedInitials: "SC",
    frequency: "5-yearly",
    description: "Comprehensive 5-year review of mitigation site performance. Requires full reassessment of nutrient loading, habitat condition, and management plan review.",
  },
  {
    id: "CMP-009",
    title: "S106 Compliance Certificate - Whiteley Farm",
    category: "Legal",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    dueDate: "2026-05-01",
    status: "Upcoming",
    assigned: "James Harris",
    assignedInitials: "JH",
    frequency: "Annual",
    description: "Annual compliance certificate to be signed by responsible body confirming all S106 obligations met.",
  },
  {
    id: "CMP-010",
    title: "Natural England Registration Fee - Fareham Woodland",
    category: "Financial",
    siteRef: "S-0008",
    siteName: "Fareham Woodland",
    dueDate: "2026-05-15",
    status: "Upcoming",
    assigned: "Sarah Croft",
    assignedInitials: "SC",
    frequency: "One-off",
    description: "BNG gain site registration fee of £639 payable to Natural England upon submission of gain site application.",
  },
  // ── Completed (5) ──
  {
    id: "CMP-011",
    title: "Annual Monitoring Report - Hamble Valley",
    category: "Monitoring",
    siteRef: "S-0003",
    siteName: "Hamble Valley",
    dueDate: "2026-01-31",
    status: "Completed",
    assigned: "Emma Walsh",
    assignedInitials: "EW",
    frequency: "Annual",
    completedDate: "2026-01-28",
    description: "Annual monitoring report submitted on time. All parameters within acceptable ranges.",
  },
  {
    id: "CMP-012",
    title: "S106 Execution - Whiteley Farm",
    category: "Legal",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    dueDate: "2025-02-28",
    status: "Completed",
    assigned: "James Harris",
    assignedInitials: "JH",
    frequency: "One-off",
    completedDate: "2025-02-05",
    description: "S106 agreement fully executed by all parties including Eastleigh Borough Council.",
  },
  {
    id: "CMP-013",
    title: "Payment Confirmation - D-0035",
    category: "Financial",
    dealRef: "D-0035",
    dealTitle: "Barratt / Botley Meadows",
    dueDate: "2026-01-20",
    status: "Completed",
    assigned: "Sarah Croft",
    assignedInitials: "SC",
    frequency: "One-off",
    completedDate: "2026-01-18",
    description: "Full payment of £87,500 received from Barratt Homes and landowner payment of £70,000 disbursed.",
  },
  {
    id: "CMP-014",
    title: "Credit Registration - D-0035",
    category: "Registration",
    dealRef: "D-0035",
    dealTitle: "Barratt / Botley Meadows",
    dueDate: "2026-02-01",
    status: "Completed",
    assigned: "James Harris",
    assignedInitials: "JH",
    frequency: "One-off",
    completedDate: "2026-01-25",
    description: "35 kg/yr nitrogen credits formally allocated on register against Barratt Homes planning condition.",
  },
  {
    id: "CMP-015",
    title: "Baseline Assessment - Test Valley",
    category: "Monitoring",
    siteRef: "S-0006",
    siteName: "Test Valley Grassland",
    dueDate: "2025-12-15",
    status: "Completed",
    assigned: "Lisa Grant",
    assignedInitials: "LG",
    frequency: "One-off",
    completedDate: "2025-12-10",
    description: "Initial baseline nutrient assessment completed and approved. Site generating 165 kg/yr credits.",
  },
];

export const overdueCount = complianceItems.filter((c) => c.status === "Overdue").length;
export const dueSoonCount = complianceItems.filter((c) => c.status === "Due Soon").length;
export const upcomingCount = complianceItems.filter((c) => c.status === "Upcoming").length;
export const completedTotal = complianceItems.filter((c) => c.status === "Completed").length;
