import type { Contact } from "./types";

export const contacts: Contact[] = [
  // ── Supply Contacts ──
  {
    id: "C-001",
    name: "Robert Whiteley",
    initials: "RW",
    company: "Whiteley Farm",
    type: "Farmer",
    side: "supply",
    email: "robert@whiteleyfarm.co.uk",
    phone: "01329 832145",
    location: "Whiteley, Hampshire",
    activeDeals: 2,
    tags: ["Nitrogen", "Solent", "Long-term partner"],
    lastActivity: "2026-03-05",
    avatarColor: "bg-emerald-500",
    role: "Farm Owner",
  },
  {
    id: "C-002",
    name: "Margaret Thornton",
    initials: "MT",
    company: "Botley Estate",
    type: "Landowner",
    side: "supply",
    email: "m.thornton@botleyestate.co.uk",
    phone: "01489 783210",
    location: "Botley, Hampshire",
    activeDeals: 1,
    tags: ["Nitrogen", "Solent", "Estate owner"],
    lastActivity: "2026-03-02",
    avatarColor: "bg-violet-500",
    role: "Estate Manager",
  },
  {
    id: "C-003",
    name: "John Hamble",
    initials: "JH",
    company: "Hamble Valley Farm",
    type: "Farmer",
    side: "supply",
    email: "john@hamblevalley.co.uk",
    phone: "01489 576823",
    location: "Hamble-le-Rice, Hampshire",
    activeDeals: 1,
    tags: ["Nitrogen", "Solent", "Fully allocated"],
    lastActivity: "2026-02-20",
    avatarColor: "bg-amber-500",
    role: "Farm Owner",
  },
  {
    id: "C-005",
    name: "David Ashford",
    initials: "DA",
    company: "Manor Fields",
    type: "Landowner",
    side: "supply",
    email: "d.ashford@manorfields.co.uk",
    phone: "01329 841567",
    location: "Fareham, Hampshire",
    activeDeals: 1,
    tags: ["Nitrogen", "Solent"],
    lastActivity: "2026-03-04",
    avatarColor: "bg-blue-500",
    role: "Landowner",
  },
  {
    id: "C-006",
    name: "Susan Marsh",
    initials: "SM",
    company: "Marsh Farmstead",
    type: "Farmer",
    side: "supply",
    email: "susan@marshfarm.co.uk",
    phone: "01264 356789",
    location: "Test Valley, Hampshire",
    activeDeals: 1,
    tags: ["Nitrogen", "Test Valley", "New prospect"],
    lastActivity: "2026-02-28",
    avatarColor: "bg-rose-500",
    role: "Farm Owner",
  },
  {
    id: "C-008",
    name: "Ian Stockbridge",
    initials: "IS",
    company: "Stockbridge Holdings",
    type: "Landowner",
    side: "supply",
    email: "ian@stockbridgeholdings.co.uk",
    phone: "01329 287654",
    location: "Fareham, Hampshire",
    activeDeals: 1,
    tags: ["BNG", "Solent", "Woodland"],
    lastActivity: "2026-03-01",
    avatarColor: "bg-teal-500",
    role: "Director",
  },
  {
    id: "C-007",
    name: "Helen Wickham",
    initials: "HW",
    company: "Hampshire Land Partners",
    type: "Land Agent",
    side: "supply",
    email: "helen@hampshireland.co.uk",
    phone: "01962 845123",
    location: "Winchester, Hampshire",
    activeDeals: 3,
    tags: ["Agent", "Multi-site", "Solent"],
    lastActivity: "2026-03-06",
    avatarColor: "bg-indigo-500",
    role: "Senior Land Agent",
  },
  {
    id: "C-009",
    name: "William Curdridge",
    initials: "WC",
    company: "Curdridge Farm",
    type: "Farmer",
    side: "supply",
    email: "william@curdridgefarm.co.uk",
    phone: "01489 785432",
    location: "Curdridge, Hampshire",
    activeDeals: 0,
    tags: ["Nitrogen", "Solent", "Prospect"],
    lastActivity: "2026-02-15",
    avatarColor: "bg-orange-500",
    role: "Farm Owner",
  },
  // ── Demand Contacts ──
  {
    id: "C-101",
    name: "Rachel Morrison",
    initials: "RM",
    company: "Taylor Wimpey",
    type: "Developer",
    side: "demand",
    email: "r.morrison@taylorwimpey.com",
    phone: "020 7355 8100",
    location: "Eastleigh, Hampshire",
    activeDeals: 2,
    tags: ["Major developer", "Solent", "Repeat buyer"],
    lastActivity: "2026-03-07",
    avatarColor: "bg-sky-500",
    role: "Land & Planning Director",
  },
  {
    id: "C-102",
    name: "Simon Barratt",
    initials: "SB",
    company: "Barratt Homes",
    type: "Developer",
    side: "demand",
    email: "s.barratt@barratthomes.co.uk",
    phone: "020 7299 4898",
    location: "Southampton, Hampshire",
    activeDeals: 1,
    tags: ["Major developer", "Solent", "Completed deal"],
    lastActivity: "2026-02-25",
    avatarColor: "bg-red-500",
    role: "Technical Director",
  },
  {
    id: "C-103",
    name: "James Bellway",
    initials: "JB",
    company: "Bellway Homes",
    type: "Developer",
    side: "demand",
    email: "j.bellway@bellway.co.uk",
    phone: "0191 217 0717",
    location: "Fareham, Hampshire",
    activeDeals: 1,
    tags: ["Developer", "Solent"],
    lastActivity: "2026-03-03",
    avatarColor: "bg-cyan-500",
    role: "Regional Director",
  },
  {
    id: "C-104",
    name: "Karen Persimmon",
    initials: "KP",
    company: "Persimmon Homes",
    type: "Developer",
    side: "demand",
    email: "k.persimmon@persimmonhomes.com",
    phone: "01904 642199",
    location: "Winchester, Hampshire",
    activeDeals: 1,
    tags: ["Developer", "Solent", "Legal stage"],
    lastActivity: "2026-03-06",
    avatarColor: "bg-fuchsia-500",
    role: "Planning Manager",
  },
  {
    id: "C-105",
    name: "Mark Linden",
    initials: "ML",
    company: "Linden Homes",
    type: "Developer",
    side: "demand",
    email: "m.linden@lindenhomes.co.uk",
    phone: "01794 378900",
    location: "Romsey, Hampshire",
    activeDeals: 1,
    tags: ["Developer", "Test Valley"],
    lastActivity: "2026-02-18",
    avatarColor: "bg-lime-500",
    role: "Land Director",
  },
  {
    id: "C-106",
    name: "Paul Miller",
    initials: "PM",
    company: "Miller Homes",
    type: "Housebuilder",
    side: "demand",
    email: "p.miller@millerhomes.co.uk",
    phone: "0131 442 0444",
    location: "Chandler's Ford, Hampshire",
    activeDeals: 1,
    tags: ["Housebuilder", "Solent"],
    lastActivity: "2026-02-22",
    avatarColor: "bg-yellow-500",
    role: "Development Manager",
  },
  {
    id: "C-107",
    name: "Sarah Wilson",
    initials: "SW",
    company: "David Wilson Homes",
    type: "Developer",
    side: "demand",
    email: "s.wilson@dwh.co.uk",
    phone: "01489 445566",
    location: "Hedge End, Hampshire",
    activeDeals: 0,
    tags: ["Developer", "Solent", "New enquiry"],
    lastActivity: "2026-03-01",
    avatarColor: "bg-pink-500",
    role: "Acquisitions Manager",
  },
];

export const supplyContacts = contacts.filter((c) => c.side === "supply");
export const demandContacts = contacts.filter((c) => c.side === "demand");
