import type { Deal } from "./types";

export const deals: Deal[] = [
  // ── Key Demo Deals ──
  {
    id: "D-0038",
    title: "Taylor Wimpey / Whiteley Farm",
    stage: "Quote Sent",
    side: "matched",
    supplyContact: "C-001",
    supplyContactName: "Robert Whiteley",
    demandContact: "C-101",
    demandContactName: "Rachel Morrison",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    unitType: "Nitrogen",
    units: 30,
    unitsLabel: "30 kg/yr",
    catchment: "Solent",
    value: 75000,
    displayValue: "£75,000",
    commission: 15000,
    commissionRate: 0.2,
    probability: 0.7,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-04-15",
    createdDate: "2026-01-10",
  },
  {
    id: "D-0035",
    title: "Barratt Homes / Botley Meadows",
    stage: "Completed",
    side: "matched",
    supplyContact: "C-002",
    supplyContactName: "Margaret Thornton",
    demandContact: "C-102",
    demandContactName: "Simon Barratt",
    siteRef: "S-0002",
    siteName: "Botley Meadows",
    unitType: "Nitrogen",
    units: 35,
    unitsLabel: "35 kg/yr",
    catchment: "Solent",
    value: 87500,
    displayValue: "£87,500",
    commission: 17500,
    commissionRate: 0.2,
    probability: 1.0,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-01-20",
    createdDate: "2025-09-15",
  },
  {
    id: "D-0042",
    title: "Taylor Wimpey Phase 2 / Botley Meadows",
    stage: "Requirements Gathered",
    side: "matched",
    supplyContact: "C-002",
    supplyContactName: "Margaret Thornton",
    demandContact: "C-101",
    demandContactName: "Rachel Morrison",
    siteRef: "S-0002",
    siteName: "Botley Meadows",
    unitType: "Nitrogen",
    units: 45,
    unitsLabel: "45 kg/yr",
    catchment: "Solent",
    value: 135000,
    displayValue: "£135,000",
    commission: 27000,
    commissionRate: 0.2,
    probability: 0.4,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-07-01",
    createdDate: "2026-02-05",
  },
  {
    id: "D-0045",
    title: "Persimmon / Manor Fields",
    stage: "Legal Drafting",
    side: "matched",
    supplyContact: "C-005",
    supplyContactName: "David Ashford",
    demandContact: "C-104",
    demandContactName: "Karen Persimmon",
    siteRef: "S-0005",
    siteName: "Manor Fields",
    unitType: "Nitrogen",
    units: 50,
    unitsLabel: "50 kg/yr",
    catchment: "Solent",
    value: 150000,
    displayValue: "£150,000",
    commission: 30000,
    commissionRate: 0.2,
    probability: 0.6,
    broker: "Sarah Croft",
    brokerInitials: "SC",
    expectedClose: "2026-05-20",
    createdDate: "2025-12-01",
  },
  // ── Remaining 14 Deals ──
  {
    id: "D-0030",
    title: "Bellway / Whiteley Farm",
    stage: "Contracts Signed",
    side: "matched",
    supplyContact: "C-001",
    supplyContactName: "Robert Whiteley",
    demandContact: "C-103",
    demandContactName: "James Bellway",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    unitType: "Nitrogen",
    units: 20,
    unitsLabel: "20 kg/yr",
    catchment: "Solent",
    value: 62000,
    displayValue: "£62,000",
    commission: 12400,
    commissionRate: 0.2,
    probability: 0.9,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-03-30",
    createdDate: "2025-10-20",
  },
  {
    id: "D-0031",
    title: "Hamble Valley / Barratt Phase 2",
    stage: "Credits Allocated",
    side: "matched",
    supplyContact: "C-003",
    supplyContactName: "John Hamble",
    demandContact: "C-102",
    demandContactName: "Simon Barratt",
    siteRef: "S-0003",
    siteName: "Hamble Valley",
    unitType: "Nitrogen",
    units: 40,
    unitsLabel: "40 kg/yr",
    catchment: "Solent",
    value: 112000,
    displayValue: "£112,000",
    commission: 22400,
    commissionRate: 0.2,
    probability: 0.95,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-03-15",
    createdDate: "2025-08-10",
  },
  {
    id: "D-0032",
    title: "Hamble Valley / Linden Homes",
    stage: "LPA Confirmed",
    side: "matched",
    supplyContact: "C-003",
    supplyContactName: "John Hamble",
    demandContact: "C-105",
    demandContactName: "Mark Linden",
    siteRef: "S-0003",
    siteName: "Hamble Valley",
    unitType: "Nitrogen",
    units: 40,
    unitsLabel: "40 kg/yr",
    catchment: "Solent",
    value: 112000,
    displayValue: "£112,000",
    commission: 22400,
    commissionRate: 0.2,
    probability: 0.98,
    broker: "Sarah Croft",
    brokerInitials: "SC",
    expectedClose: "2026-03-10",
    createdDate: "2025-07-05",
  },
  {
    id: "D-0033",
    title: "Miller Homes / Manor Fields",
    stage: "Payment Pending",
    side: "matched",
    supplyContact: "C-005",
    supplyContactName: "David Ashford",
    demandContact: "C-106",
    demandContactName: "Paul Miller",
    siteRef: "S-0005",
    siteName: "Manor Fields",
    unitType: "Nitrogen",
    units: 50,
    unitsLabel: "50 kg/yr",
    catchment: "Solent",
    value: 150000,
    displayValue: "£150,000",
    commission: 30000,
    commissionRate: 0.2,
    probability: 0.85,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-04-01",
    createdDate: "2025-11-15",
  },
  {
    id: "D-0034",
    title: "David Wilson / Botley Meadows",
    stage: "Prospecting",
    side: "demand",
    supplyContact: "",
    supplyContactName: "",
    demandContact: "C-107",
    demandContactName: "Sarah Wilson",
    siteRef: "",
    siteName: "",
    unitType: "Nitrogen",
    units: 25,
    unitsLabel: "25 kg/yr",
    catchment: "Solent",
    value: 62500,
    displayValue: "£62,500",
    commission: 12500,
    commissionRate: 0.2,
    probability: 0.15,
    broker: "Tom Jenkins",
    brokerInitials: "TJ",
    expectedClose: "2026-09-01",
    createdDate: "2026-03-01",
  },
  {
    id: "D-0036",
    title: "Test Valley / Taylor Wimpey",
    stage: "Initial Contact",
    side: "supply",
    supplyContact: "C-006",
    supplyContactName: "Susan Marsh",
    demandContact: "",
    demandContactName: "",
    siteRef: "S-0006",
    siteName: "Test Valley Grassland",
    unitType: "Nitrogen",
    units: 80,
    unitsLabel: "80 kg/yr",
    catchment: "Test Valley",
    value: 184000,
    displayValue: "£184,000",
    commission: 36800,
    commissionRate: 0.2,
    probability: 0.2,
    broker: "Sarah Croft",
    brokerInitials: "SC",
    expectedClose: "2026-10-01",
    createdDate: "2026-02-20",
  },
  {
    id: "D-0037",
    title: "Fareham Woodland BNG / TBD",
    stage: "Prospecting",
    side: "supply",
    supplyContact: "C-008",
    supplyContactName: "Ian Stockbridge",
    demandContact: "",
    demandContactName: "",
    siteRef: "S-0008",
    siteName: "Fareham Woodland",
    unitType: "BNG",
    units: 22.5,
    unitsLabel: "18.0 area HU + 4.5 hedgerow HU",
    catchment: "Solent",
    value: 562500,
    displayValue: "£562,500",
    commission: 101250,
    commissionRate: 0.18,
    probability: 0.1,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-12-01",
    createdDate: "2026-02-10",
    bngAllocation: [
      {
        category: "area",
        categoryLabel: "Areas",
        habitatType: "Lowland Mixed Deciduous Woodland",
        units: 18.0,
        unitLabel: "area HUs",
        pricePerUnit: 25000,
        value: 450000,
      },
      {
        category: "hedgerow",
        categoryLabel: "Hedgerows",
        habitatType: "Native Species-rich Hedgerow",
        units: 4.5,
        unitLabel: "hedgerow HUs",
        pricePerUnit: 25000,
        value: 112500,
      },
    ],
  },
  {
    id: "D-0039",
    title: "Whiteley Farm / Persimmon Phase 2",
    stage: "Site Matched",
    side: "matched",
    supplyContact: "C-001",
    supplyContactName: "Robert Whiteley",
    demandContact: "C-104",
    demandContactName: "Karen Persimmon",
    siteRef: "S-0001",
    siteName: "Whiteley Farm",
    unitType: "Nitrogen",
    units: 15,
    unitsLabel: "15 kg/yr",
    catchment: "Solent",
    value: 48000,
    displayValue: "£48,000",
    commission: 9600,
    commissionRate: 0.2,
    probability: 0.35,
    broker: "Tom Jenkins",
    brokerInitials: "TJ",
    expectedClose: "2026-06-15",
    createdDate: "2026-01-28",
  },
  {
    id: "D-0040",
    title: "Bellway / Manor Fields Phase 2",
    stage: "Quote Accepted",
    side: "matched",
    supplyContact: "C-005",
    supplyContactName: "David Ashford",
    demandContact: "C-103",
    demandContactName: "James Bellway",
    siteRef: "S-0005",
    siteName: "Manor Fields",
    unitType: "Nitrogen",
    units: 20,
    unitsLabel: "20 kg/yr",
    catchment: "Solent",
    value: 60000,
    displayValue: "£60,000",
    commission: 12000,
    commissionRate: 0.2,
    probability: 0.65,
    broker: "Sarah Croft",
    brokerInitials: "SC",
    expectedClose: "2026-05-01",
    createdDate: "2025-12-10",
  },
  {
    id: "D-0041",
    title: "Curdridge / Hampshire Land Partners",
    stage: "Initial Contact",
    side: "supply",
    supplyContact: "C-009",
    supplyContactName: "William Curdridge",
    demandContact: "",
    demandContactName: "",
    siteRef: "",
    siteName: "",
    unitType: "Nitrogen",
    units: 50,
    unitsLabel: "50 kg/yr",
    catchment: "Solent",
    value: 125000,
    displayValue: "£125,000",
    commission: 25000,
    commissionRate: 0.2,
    probability: 0.1,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2027-01-01",
    createdDate: "2026-02-15",
  },
  {
    id: "D-0043",
    title: "Manor Fields / David Wilson",
    stage: "Requirements Gathered",
    side: "demand",
    supplyContact: "",
    supplyContactName: "",
    demandContact: "C-107",
    demandContactName: "Sarah Wilson",
    siteRef: "",
    siteName: "",
    unitType: "Nitrogen",
    units: 35,
    unitsLabel: "35 kg/yr",
    catchment: "Solent",
    value: 105000,
    displayValue: "£105,000",
    commission: 21000,
    commissionRate: 0.2,
    probability: 0.25,
    broker: "Tom Jenkins",
    brokerInitials: "TJ",
    expectedClose: "2026-08-01",
    createdDate: "2026-02-25",
  },
  {
    id: "D-0044",
    title: "Test Valley / Linden Homes",
    stage: "Prospecting",
    side: "demand",
    supplyContact: "",
    supplyContactName: "",
    demandContact: "C-105",
    demandContactName: "Mark Linden",
    siteRef: "",
    siteName: "",
    unitType: "Nitrogen",
    units: 60,
    unitsLabel: "60 kg/yr",
    catchment: "Test Valley",
    value: 138000,
    displayValue: "£138,000",
    commission: 27600,
    commissionRate: 0.2,
    probability: 0.1,
    broker: "Sarah Croft",
    brokerInitials: "SC",
    expectedClose: "2026-11-01",
    createdDate: "2026-03-05",
  },
  {
    id: "D-0046",
    title: "Payment Received / Hamble",
    stage: "Payment Received",
    side: "matched",
    supplyContact: "C-003",
    supplyContactName: "John Hamble",
    demandContact: "C-106",
    demandContactName: "Paul Miller",
    siteRef: "S-0003",
    siteName: "Hamble Valley",
    unitType: "Nitrogen",
    units: 30,
    unitsLabel: "30 kg/yr",
    catchment: "Solent",
    value: 84000,
    displayValue: "£84,000",
    commission: 16800,
    commissionRate: 0.2,
    probability: 0.95,
    broker: "James Harris",
    brokerInitials: "JH",
    expectedClose: "2026-03-20",
    createdDate: "2025-09-01",
  },
];

export const pipelineValue = 8_400_000;

export const activeDealsCount = 42;

export const dealsByStage = deals.reduce<Record<string, Deal[]>>((acc, d) => {
  (acc[d.stage] ??= []).push(d);
  return acc;
}, {});

export const commissionYTD = 312_500;
