import type { Document } from "./types";

export const documents: Document[] = [
  {
    id: "DOC-001",
    name: "S106 Agreement — Whiteley Farm",
    type: "S106",
    linkedEntityType: "site",
    linkedEntityId: "S-0001",
    linkedEntityLabel: "S-0001 Whiteley Farm",
    uploadedBy: "James Harris",
    uploadedDate: "2025-01-15",
    status: "Completed",
    fileSize: "2.4 MB",
    signatories: [
      { name: "Robert Whiteley", signed: true, signedDate: "2025-01-20" },
      { name: "Eastleigh Borough Council", signed: true, signedDate: "2025-02-05" },
    ],
    versions: [
      { version: 1, date: "2025-01-15", author: "James Harris" },
      { version: 2, date: "2025-01-18", author: "Legal Team" },
      { version: 3, date: "2025-01-19", author: "James Harris" },
    ],
  },
  {
    id: "DOC-002",
    name: "S106 Agreement — Botley Meadows",
    type: "S106",
    linkedEntityType: "site",
    linkedEntityId: "S-0002",
    linkedEntityLabel: "S-0002 Botley Meadows",
    uploadedBy: "James Harris",
    uploadedDate: "2025-03-20",
    status: "Completed",
    fileSize: "2.1 MB",
    signatories: [
      { name: "Margaret Thornton", signed: true, signedDate: "2025-03-25" },
      { name: "Eastleigh Borough Council", signed: true, signedDate: "2025-04-10" },
    ],
    versions: [
      { version: 1, date: "2025-03-20", author: "James Harris" },
      { version: 2, date: "2025-03-22", author: "Legal Team" },
    ],
  },
  {
    id: "DOC-003",
    name: "S106 Agreement — Hamble Valley",
    type: "S106",
    linkedEntityType: "site",
    linkedEntityId: "S-0003",
    linkedEntityLabel: "S-0003 Hamble Valley",
    uploadedBy: "Sarah Croft",
    uploadedDate: "2024-10-15",
    status: "Completed",
    fileSize: "1.9 MB",
    signatories: [
      { name: "John Hamble", signed: true, signedDate: "2024-10-20" },
      { name: "Eastleigh Borough Council", signed: true, signedDate: "2024-11-01" },
    ],
    versions: [
      { version: 1, date: "2024-10-15", author: "Sarah Croft" },
    ],
  },
  {
    id: "DOC-004",
    name: "Conservation Covenant — Fareham Woodland",
    type: "Conservation Covenant",
    linkedEntityType: "site",
    linkedEntityId: "S-0008",
    linkedEntityLabel: "S-0008 Fareham Woodland",
    uploadedBy: "James Harris",
    uploadedDate: "2026-01-20",
    status: "Signed",
    fileSize: "3.2 MB",
    signatories: [
      { name: "Ian Stockbridge", signed: true, signedDate: "2026-02-01" },
      { name: "Natural England", signed: false },
    ],
    versions: [
      { version: 1, date: "2026-01-20", author: "James Harris" },
      { version: 2, date: "2026-01-28", author: "Legal Team" },
    ],
  },
  {
    id: "DOC-005",
    name: "Heads of Terms — Manor Fields",
    type: "Heads of Terms",
    linkedEntityType: "site",
    linkedEntityId: "S-0005",
    linkedEntityLabel: "S-0005 Manor Fields",
    uploadedBy: "Sarah Croft",
    uploadedDate: "2025-07-20",
    status: "Signed",
    fileSize: "890 KB",
    signatories: [
      { name: "David Ashford", signed: true, signedDate: "2025-07-25" },
    ],
    versions: [
      { version: 1, date: "2025-07-20", author: "Sarah Croft" },
    ],
  },
  {
    id: "DOC-006",
    name: "Purchase Agreement — Barratt / Botley",
    type: "Purchase Agreement",
    linkedEntityType: "deal",
    linkedEntityId: "D-0035",
    linkedEntityLabel: "D-0035 Barratt / Botley Meadows",
    uploadedBy: "James Harris",
    uploadedDate: "2025-12-10",
    status: "Completed",
    fileSize: "1.5 MB",
    signatories: [
      { name: "Margaret Thornton", signed: true, signedDate: "2025-12-15" },
      { name: "Simon Barratt", signed: true, signedDate: "2025-12-18" },
    ],
    versions: [
      { version: 1, date: "2025-12-10", author: "James Harris" },
      { version: 2, date: "2025-12-12", author: "Legal Team" },
      { version: 3, date: "2025-12-14", author: "James Harris" },
    ],
  },
  {
    id: "DOC-007",
    name: "Purchase Agreement — Taylor Wimpey / Whiteley",
    type: "Purchase Agreement",
    linkedEntityType: "deal",
    linkedEntityId: "D-0038",
    linkedEntityLabel: "D-0038 Taylor Wimpey / Whiteley Farm",
    uploadedBy: "James Harris",
    uploadedDate: "2026-02-20",
    status: "Draft",
    fileSize: "1.2 MB",
    versions: [
      { version: 1, date: "2026-02-20", author: "James Harris" },
    ],
  },
  {
    id: "DOC-008",
    name: "HMMP — Fareham Woodland",
    type: "HMMP",
    linkedEntityType: "site",
    linkedEntityId: "S-0008",
    linkedEntityLabel: "S-0008 Fareham Woodland",
    uploadedBy: "David Park",
    uploadedDate: "2026-02-10",
    status: "Draft",
    fileSize: "4.8 MB",
    versions: [
      { version: 1, date: "2026-02-10", author: "David Park" },
    ],
  },
  {
    id: "DOC-009",
    name: "Survey Report — Whiteley Farm NN Baseline",
    type: "Survey Report",
    linkedEntityType: "site",
    linkedEntityId: "S-0001",
    linkedEntityLabel: "S-0001 Whiteley Farm",
    uploadedBy: "Sarah Chen",
    uploadedDate: "2025-05-25",
    status: "Completed",
    fileSize: "6.3 MB",
    versions: [
      { version: 1, date: "2025-05-25", author: "Sarah Chen" },
    ],
  },
  {
    id: "DOC-010",
    name: "Metric Calculation — Fareham Woodland BNG",
    type: "Metric Calculation",
    linkedEntityType: "site",
    linkedEntityId: "S-0008",
    linkedEntityLabel: "S-0008 Fareham Woodland",
    uploadedBy: "David Park",
    uploadedDate: "2026-02-08",
    status: "Completed",
    fileSize: "1.1 MB",
    versions: [
      { version: 1, date: "2026-02-08", author: "David Park" },
    ],
  },
  {
    id: "DOC-011",
    name: "Reservation Agreement — Taylor Wimpey Phase 2",
    type: "Reservation Agreement",
    linkedEntityType: "deal",
    linkedEntityId: "D-0042",
    linkedEntityLabel: "D-0042 Taylor Wimpey Phase 2",
    uploadedBy: "James Harris",
    uploadedDate: "2026-02-28",
    status: "Sent",
    fileSize: "780 KB",
    signatories: [
      { name: "Rachel Morrison", signed: false },
    ],
    versions: [
      { version: 1, date: "2026-02-28", author: "James Harris" },
    ],
  },
  {
    id: "DOC-012",
    name: "Invoice — Barratt / Botley Meadows",
    type: "Invoice",
    linkedEntityType: "deal",
    linkedEntityId: "D-0035",
    linkedEntityLabel: "D-0035 Barratt / Botley Meadows",
    uploadedBy: "James Harris",
    uploadedDate: "2026-01-05",
    status: "Completed",
    fileSize: "245 KB",
    versions: [
      { version: 1, date: "2026-01-05", author: "James Harris" },
    ],
  },
];
