import type { Site } from "./types";

export const sites: Site[] = [
  {
    ref: "S-0001",
    name: "Whiteley Farm",
    status: "Active",
    contact: "C-001",
    contactName: "Robert Whiteley",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 95,
    totalLabel: "95 kg/yr",
    allocated: 50,
    allocatedLabel: "50 kg/yr",
    available: 45,
    availableLabel: "45 kg/yr",
    price: 3200,
    priceLabel: "£3,200/kg",
    lpa: "Eastleigh",
    lat: 50.8831,
    lng: -1.2665,
    address: "Whiteley Farm, Whiteley Lane, Fareham PO15 7LR",
    areaHectares: 60,
    currentUse: "Arable",
    soilType: "Clay loam",
    registrationRef: "NN-SOL-2025-0012",
    registeredDate: "2025-06-15",
    legalAgreement: "S106",
    commitmentYears: 80,
  },
  {
    ref: "S-0002",
    name: "Botley Meadows",
    status: "Active",
    contact: "C-002",
    contactName: "Margaret Thornton",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 120,
    totalLabel: "120 kg/yr",
    allocated: 35,
    allocatedLabel: "35 kg/yr",
    available: 85,
    availableLabel: "85 kg/yr",
    price: 2500,
    priceLabel: "£2,500/kg",
    lpa: "Eastleigh",
    lat: 50.9145,
    lng: -1.2890,
    address: "Botley Meadows, Mill Lane, Botley SO30 2HA",
    areaHectares: 85,
    currentUse: "Pasture",
    soilType: "Alluvial clay",
    registrationRef: "NN-SOL-2025-0008",
    registeredDate: "2025-04-22",
    legalAgreement: "S106",
    commitmentYears: 80,
  },
  {
    ref: "S-0003",
    name: "Hamble Valley",
    status: "Fully Allocated",
    contact: "C-003",
    contactName: "John Hamble",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 80,
    totalLabel: "80 kg/yr",
    allocated: 80,
    allocatedLabel: "80 kg/yr",
    available: 0,
    availableLabel: "0 kg/yr",
    price: 2800,
    priceLabel: "£2,800/kg",
    lpa: "Eastleigh",
    lat: 50.8720,
    lng: -1.3150,
    address: "Hamble Valley Farm, Hamble Lane, Hamble SO31 4JD",
    areaHectares: 45,
    currentUse: "Mixed grazing",
    soilType: "Sandy loam",
    registrationRef: "NN-SOL-2024-0035",
    registeredDate: "2024-11-10",
    legalAgreement: "S106",
    commitmentYears: 80,
  },
  {
    ref: "S-0005",
    name: "Manor Fields",
    status: "Active",
    contact: "C-005",
    contactName: "David Ashford",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 95,
    totalLabel: "95 kg/yr",
    allocated: 50,
    allocatedLabel: "50 kg/yr",
    available: 45,
    availableLabel: "45 kg/yr",
    price: 3000,
    priceLabel: "£3,000/kg",
    lpa: "Fareham",
    lat: 50.8560,
    lng: -1.1890,
    address: "Manor Fields, Titchfield Lane, Fareham PO14 4AJ",
    areaHectares: 55,
    currentUse: "Arable",
    soilType: "Chalk over clay",
    registrationRef: "NN-SOL-2025-0019",
    registeredDate: "2025-08-03",
    legalAgreement: "S106",
    commitmentYears: 80,
  },
  {
    ref: "S-0006",
    name: "Test Valley Grassland",
    status: "Registered",
    contact: "C-006",
    contactName: "Susan Marsh",
    catchment: "Test Valley",
    unitType: "Nitrogen",
    total: 165,
    totalLabel: "165 kg/yr",
    allocated: 0,
    allocatedLabel: "0 kg/yr",
    available: 165,
    availableLabel: "165 kg/yr",
    price: 2300,
    priceLabel: "£2,300/kg",
    lpa: "Test Valley",
    lat: 51.0920,
    lng: -1.4850,
    address: "Marsh Farmstead, Stockbridge Road, Test Valley SO20 6HE",
    areaHectares: 110,
    currentUse: "Pasture",
    soilType: "Chalk grassland",
    registrationRef: "NN-TV-2026-0002",
    registeredDate: "2026-01-18",
  },
  {
    ref: "S-0008",
    name: "Fareham Woodland",
    status: "Under Assessment",
    contact: "C-008",
    contactName: "Ian Stockbridge",
    catchment: "Solent",
    unitType: "BNG",
    total: 22.5,
    totalLabel: "22.5 units",
    allocated: 0,
    allocatedLabel: "0 units",
    available: 22.5,
    availableLabel: "22.5 units",
    price: 25000,
    priceLabel: "£25,000/unit",
    lpa: "Fareham",
    lat: 50.8450,
    lng: -1.2100,
    address: "Fareham Woodland, Cams Hill, Fareham PO16 8AB",
    areaHectares: 18,
    currentUse: "Woodland",
    soilType: "Clay with flints",
    legalAgreement: "Conservation Covenant",
  },
];

export const totalNitrogenCredits = sites
  .filter((s) => s.unitType === "Nitrogen")
  .reduce((sum, s) => sum + s.total, 0);

export const availableNitrogenCredits = sites
  .filter((s) => s.unitType === "Nitrogen")
  .reduce((sum, s) => sum + s.available, 0);

export const totalBNGUnits = sites
  .filter((s) => s.unitType === "BNG")
  .reduce((sum, s) => sum + s.total, 0);

export const availableBNGUnits = sites
  .filter((s) => s.unitType === "BNG")
  .reduce((sum, s) => sum + s.available, 0);
