import type { Site } from "./types";

export const sites: Site[] = [
  {
    ref: "S-0001",
    name: "Whiteley Farm",
    status: "Active",
    contact: "C-001",
    contactName: "Robert Whiteley",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 95,
    totalLabel: "95 kg/yr",
    allocated: 50,
    allocatedLabel: "50 kg/yr",
    available: 45,
    availableLabel: "45 kg/yr",
    price: 3200,
    priceLabel: "£3,200/kg",
    lpa: "Eastleigh",
    lat: 50.8831,
    lng: -1.2665,
    address: "Whiteley Farm, Whiteley Lane, Fareham PO15 7LR",
    areaHectares: 60,
    currentUse: "Arable",
    soilType: "Clay loam",
    registrationRef: "NN-SOL-2025-0012",
    registeredDate: "2025-06-15",
    legalAgreement: "S106",
    commitmentYears: 80,
    baselineLoading: 340,
    proposedLoading: 245,
    mitigationType: "Land Use Change: Arable → Permanent Grassland + Riparian Buffer Strips",
    nationalCharacterArea: "South Hampshire Coast",
    lnrsArea: "Hampshire and the Isle of Wight",
    lsoa: "Fareham 012B",
    imdDecile: 5,
  },
  {
    ref: "S-0002",
    name: "Botley Meadows",
    status: "Active",
    contact: "C-002",
    contactName: "Margaret Thornton",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 120,
    totalLabel: "120 kg/yr",
    allocated: 35,
    allocatedLabel: "35 kg/yr",
    available: 85,
    availableLabel: "85 kg/yr",
    price: 2500,
    priceLabel: "£2,500/kg",
    lpa: "Eastleigh",
    lat: 50.9145,
    lng: -1.2890,
    address: "Botley Meadows, Mill Lane, Botley SO30 2HA",
    areaHectares: 85,
    currentUse: "Pasture",
    soilType: "Alluvial clay",
    registrationRef: "NN-SOL-2025-0008",
    registeredDate: "2025-04-22",
    legalAgreement: "S106",
    commitmentYears: 80,
    baselineLoading: 425,
    proposedLoading: 305,
    mitigationType: "Land Use Change: Dairy Pasture → Extensive Grassland + Wetland Margins",
    nationalCharacterArea: "South Hampshire Coast",
    lnrsArea: "Hampshire and the Isle of Wight",
    lsoa: "Eastleigh 008A",
    imdDecile: 4,
  },
  {
    ref: "S-0003",
    name: "Hamble Valley",
    status: "Fully Allocated",
    contact: "C-003",
    contactName: "John Hamble",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 80,
    totalLabel: "80 kg/yr",
    allocated: 80,
    allocatedLabel: "80 kg/yr",
    available: 0,
    availableLabel: "0 kg/yr",
    price: 2800,
    priceLabel: "£2,800/kg",
    lpa: "Eastleigh",
    lat: 50.8720,
    lng: -1.3150,
    address: "Hamble Valley Farm, Hamble Lane, Hamble SO31 4JD",
    areaHectares: 45,
    currentUse: "Mixed grazing",
    soilType: "Sandy loam",
    registrationRef: "NN-SOL-2024-0035",
    registeredDate: "2024-11-10",
    legalAgreement: "S106",
    commitmentYears: 80,
    baselineLoading: 180,
    proposedLoading: 100,
    mitigationType: "Management Change: Mixed Grazing → Hay Meadow, Reduced Stocking Density",
    nationalCharacterArea: "South Hampshire Coast",
    lnrsArea: "Hampshire and the Isle of Wight",
    lsoa: "Eastleigh 011C",
    imdDecile: 5,
  },
  {
    ref: "S-0005",
    name: "Manor Fields",
    status: "Active",
    contact: "C-005",
    contactName: "David Ashford",
    catchment: "Solent",
    unitType: "Nitrogen",
    total: 95,
    totalLabel: "95 kg/yr",
    allocated: 50,
    allocatedLabel: "50 kg/yr",
    available: 45,
    availableLabel: "45 kg/yr",
    price: 3000,
    priceLabel: "£3,000/kg",
    lpa: "Fareham",
    lat: 50.8560,
    lng: -1.1890,
    address: "Manor Fields, Titchfield Lane, Fareham PO14 4AJ",
    areaHectares: 55,
    currentUse: "Arable",
    soilType: "Chalk over clay",
    registrationRef: "NN-SOL-2025-0019",
    registeredDate: "2025-08-03",
    legalAgreement: "S106",
    commitmentYears: 80,
    baselineLoading: 330,
    proposedLoading: 235,
    mitigationType: "Land Use Change: Arable → Species-rich Chalk Grassland",
    nationalCharacterArea: "Hampshire Downs",
    lnrsArea: "Hampshire and the Isle of Wight",
    lsoa: "Fareham 018D",
    imdDecile: 7,
  },
  {
    ref: "S-0006",
    name: "Test Valley Grassland",
    status: "Registered",
    contact: "C-006",
    contactName: "Susan Marsh",
    catchment: "Test Valley",
    unitType: "Nitrogen",
    total: 165,
    totalLabel: "165 kg/yr",
    allocated: 0,
    allocatedLabel: "0 kg/yr",
    available: 165,
    availableLabel: "165 kg/yr",
    price: 2300,
    priceLabel: "£2,300/kg",
    lpa: "Test Valley",
    lat: 51.0920,
    lng: -1.4850,
    address: "Marsh Farmstead, Stockbridge Road, Test Valley SO20 6HE",
    areaHectares: 110,
    currentUse: "Pasture",
    soilType: "Chalk grassland",
    registrationRef: "NN-TV-2026-0002",
    registeredDate: "2026-01-18",
    baselineLoading: 550,
    proposedLoading: 385,
    mitigationType: "Management Change: Intensive Dairy → Extensive Grazing + Chalk Stream Buffers",
    nationalCharacterArea: "Hampshire Downs",
    lnrsArea: "Hampshire and the Isle of Wight",
    lsoa: "Test Valley 006A",
    imdDecile: 8,
  },
  {
    ref: "S-0008",
    name: "Fareham Woodland",
    status: "Under Assessment",
    contact: "C-008",
    contactName: "Ian Stockbridge",
    catchment: "Solent",
    unitType: "BNG",
    total: 206.0,
    totalLabel: "206.0 area HUs",
    allocated: 0,
    allocatedLabel: "0 units",
    available: 206.0,
    availableLabel: "206.0 area HUs",
    price: 25000,
    priceLabel: "£25,000/unit",
    lpa: "Fareham",
    lat: 50.8450,
    lng: -1.2100,
    address: "Fareham Woodland, Cams Hill, Fareham PO16 8AB",
    areaHectares: 18,
    currentUse: "Conifer plantation with modified understorey",
    soilType: "Clay with flints",
    legalAgreement: "Conservation Covenant",
    bgsReference: "BGS-040326001",
    nationalCharacterArea: "South Hampshire Coast",
    lnrsArea: "Hampshire and the Isle of Wight",
    lsoa: "Fareham 014A",
    imdDecile: 6,
    enhancementStartDate: "2026-06-01",
    metricVersion: "Statutory Metric 1.0",
    hmmpStatus: "draft",
    habitatSummary: [
      {
        category: "area",
        categoryLabel: "Areas",
        baselineParcelCount: 8,
        improvementParcelCount: 8,
        baselineSize: 18.0,
        improvementSize: 18.0,
        retainedSize: 0.0,
        sizeUnit: "ha",
        baselineUnits: 59.0,
        improvementUnits: 206.0,
        unitGain: 147.0,
        allocatedUnits: 0.0,
        allocatedPercent: 0.0,
      },
      {
        category: "hedgerow",
        categoryLabel: "Hedgerows",
        baselineParcelCount: 1,
        improvementParcelCount: 2,
        baselineSize: 0.6,
        improvementSize: 1.2,
        retainedSize: 0.6,
        sizeUnit: "km",
        baselineUnits: 1.2,
        improvementUnits: 13.5,
        unitGain: 12.3,
        allocatedUnits: 0.0,
        allocatedPercent: 0.0,
      },
    ],
    baselineHabitats: [
      {
        id: "BP-001",
        phase: "baseline",
        category: "area",
        broadHabitatType: "Woodland",
        specificHabitatType: "Woodland and Forest; Conifer Plantation",
        distinctiveness: "low",
        distinctivenessScore: 2,
        condition: "poor",
        conditionScore: 1.0,
        strategicSignificance: "low",
        significanceMultiplier: 1.0,
        parcelCount: 3,
        size: 11.0,
        sizeUnit: "ha",
        biodiversityUnits: 33.0,
        unitGain: null,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: 0.0,
        temporalRisk: null,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "BP-002",
        phase: "baseline",
        category: "area",
        broadHabitatType: "Scrub",
        specificHabitatType: "Scrub",
        distinctiveness: "medium",
        distinctivenessScore: 4,
        condition: "poor",
        conditionScore: 1.0,
        strategicSignificance: "low",
        significanceMultiplier: 1.0,
        parcelCount: 2,
        size: 4.5,
        sizeUnit: "ha",
        biodiversityUnits: 18.0,
        unitGain: null,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: 0.0,
        temporalRisk: null,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "BP-003",
        phase: "baseline",
        category: "area",
        broadHabitatType: "Scrub",
        specificHabitatType: "Bramble Scrub",
        distinctiveness: "medium",
        distinctivenessScore: 4,
        condition: "poor",
        conditionScore: 1.0,
        strategicSignificance: "low",
        significanceMultiplier: 1.0,
        parcelCount: 1,
        size: 1.5,
        sizeUnit: "ha",
        biodiversityUnits: 6.0,
        unitGain: null,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: 0.0,
        temporalRisk: null,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "BP-004",
        phase: "baseline",
        category: "area",
        broadHabitatType: "Grassland",
        specificHabitatType: "Modified Grassland",
        distinctiveness: "low",
        distinctivenessScore: 2,
        condition: "poor",
        conditionScore: 1.0,
        strategicSignificance: "low",
        significanceMultiplier: 1.0,
        parcelCount: 2,
        size: 1.0,
        sizeUnit: "ha",
        biodiversityUnits: 2.0,
        unitGain: null,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: 0.0,
        temporalRisk: null,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "BP-005",
        phase: "baseline",
        category: "hedgerow",
        broadHabitatType: "Hedgerow",
        specificHabitatType: "Hedgerow; No Associated Trees",
        distinctiveness: "low",
        distinctivenessScore: 2,
        condition: "poor",
        conditionScore: 1.0,
        strategicSignificance: "low",
        significanceMultiplier: 1.0,
        parcelCount: 1,
        size: 0.6,
        sizeUnit: "km",
        biodiversityUnits: 1.2,
        unitGain: null,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: 0.6,
        temporalRisk: null,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
    ],
    improvementHabitats: [
      {
        id: "IP-001",
        phase: "improvement",
        category: "area",
        broadHabitatType: "Woodland",
        specificHabitatType: "Lowland Mixed Deciduous Woodland",
        distinctiveness: "v_high",
        distinctivenessScore: 8,
        condition: "moderate",
        conditionScore: 2.0,
        strategicSignificance: "medium",
        significanceMultiplier: 1.1,
        parcelCount: 3,
        size: 11.0,
        sizeUnit: "ha",
        biodiversityUnits: 145.2,
        unitGain: 112.2,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: null,
        temporalRisk: 0.75,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "IP-002",
        phase: "improvement",
        category: "area",
        broadHabitatType: "Woodland",
        specificHabitatType: "Woodland Edge",
        distinctiveness: "medium",
        distinctivenessScore: 4,
        condition: "fairly_good",
        conditionScore: 2.5,
        strategicSignificance: "medium",
        significanceMultiplier: 1.1,
        parcelCount: 2,
        size: 4.5,
        sizeUnit: "ha",
        biodiversityUnits: 42.1,
        unitGain: 24.1,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: null,
        temporalRisk: 0.85,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "IP-003",
        phase: "improvement",
        category: "area",
        broadHabitatType: "Scrub",
        specificHabitatType: "Scrub Mosaic (Mixed Scrub)",
        distinctiveness: "medium",
        distinctivenessScore: 4,
        condition: "moderate",
        conditionScore: 2.0,
        strategicSignificance: "low",
        significanceMultiplier: 1.0,
        parcelCount: 2,
        size: 1.5,
        sizeUnit: "ha",
        biodiversityUnits: 10.8,
        unitGain: null,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: null,
        temporalRisk: 0.90,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "IP-004",
        phase: "improvement",
        category: "area",
        broadHabitatType: "Grassland",
        specificHabitatType: "Species-rich Neutral Grassland",
        distinctiveness: "medium",
        distinctivenessScore: 4,
        condition: "moderate",
        conditionScore: 2.0,
        strategicSignificance: "medium",
        significanceMultiplier: 1.1,
        parcelCount: 1,
        size: 1.0,
        sizeUnit: "ha",
        biodiversityUnits: 7.9,
        unitGain: null,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: null,
        temporalRisk: 0.90,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
      {
        id: "IP-005",
        phase: "improvement",
        category: "hedgerow",
        broadHabitatType: "Hedgerow",
        specificHabitatType: "Hedgerow; Native Species-rich",
        distinctiveness: "high",
        distinctivenessScore: 6,
        condition: "moderate",
        conditionScore: 2.0,
        strategicSignificance: "medium",
        significanceMultiplier: 1.1,
        parcelCount: 2,
        size: 1.2,
        sizeUnit: "km",
        biodiversityUnits: 13.5,
        unitGain: 12.3,
        allocatedSize: 0,
        allocatedPercent: 0,
        allocatedUnits: 0,
        retainedSize: null,
        temporalRisk: 0.85,
        spatialRisk: null,
        difficultyMultiplier: null,
      },
    ],
    siteAllocations: [],
  },
];

export const totalNitrogenCredits = sites
  .filter((s) => s.unitType === "Nitrogen")
  .reduce((sum, s) => sum + s.total, 0);

export const availableNitrogenCredits = sites
  .filter((s) => s.unitType === "Nitrogen")
  .reduce((sum, s) => sum + s.available, 0);

export const totalBNGUnits = sites
  .filter((s) => s.unitType === "BNG")
  .reduce((sum, s) => sum + s.total, 0);

export const availableBNGUnits = sites
  .filter((s) => s.unitType === "BNG")
  .reduce((sum, s) => sum + s.available, 0);
