import type { ModuleManifest } from '@/shared/module-system/types'

export const clientPortalManifest: ModuleManifest = {
  slug: 'client-portal',
  name: 'Client Portal',
  description: 'Client engagement management with proposals, milestones, deliverables, invoices, and approvals',
  icon: 'Briefcase',
  category: 'operations',
  dependencies: ['customer', 'payment'],
  routes: [
    { path: '/admin/clients', label: 'Clients', permission: 'engagement:read' },
    { path: '/admin/clients/new', label: 'New Engagement', permission: 'engagement:write' },
    { path: '/admin/clients/[engagementId]', label: 'Engagement Detail', permission: 'engagement:read' },
    { path: '/admin/clients/[engagementId]/proposals/new', label: 'New Proposal', permission: 'proposal:write' },
  ],
  sidebarItems: [
    {
      title: 'Clients',
      href: '/admin/clients',
      icon: 'Briefcase',
      section: 'Operations',
      permission: 'engagement:read',
    },
  ],
  analyticsWidgets: [
    {
      id: 'active-engagements',
      type: 'kpi',
      label: 'Active Engagements',
      size: '1x1',
      dataSource: { procedure: 'clientPortal.admin.listEngagements' },
    },
    {
      id: 'pipeline-value',
      type: 'kpi',
      label: 'Pipeline Value',
      size: '1x1',
      dataSource: { procedure: 'clientPortal.admin.listEngagements' },
    },
  ],
  permissions: [
    'engagement:read',
    'engagement:write',
    'proposal:read',
    'proposal:write',
    'milestone:read',
    'milestone:write',
    'deliverable:read',
    'deliverable:write',
    'invoice:read',
    'invoice:write',
    'approval:read',
    'approval:write',
  ],
  eventsProduced: [
    'client-portal/proposal.sent',
    'client-portal/proposal.approved',
    'client-portal/proposal.declined',
    'client-portal/invoice.sent',
    'client-portal/invoice.paid',
    'client-portal/deliverable.shared',
    'client-portal/approval.requested',
    'client-portal/approval.responded',
  ],
  eventsConsumed: [],
  isCore: false,
  availability: 'standard',
  auditResources: [
    'engagement',
    'proposal',
    'milestone',
    'deliverable',
    'invoice',
    'approval',
  ],
}
